BEGIN;

-- Cross-instance fixed-window login throttling. Keys are one-way hashes generated by the
-- application; raw visitor identifiers are never persisted here.
CREATE TABLE auth_rate_limit_windows (
  route text NOT NULL,
  key_hash text NOT NULL,
  window_started_at timestamptz NOT NULL,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (route, key_hash)
);
CREATE INDEX auth_rate_limit_windows_updated_idx ON auth_rate_limit_windows(updated_at);

COMMENT ON TABLE auth_rate_limit_windows IS 'Privacy-minimised, cross-instance fixed-window authentication throttles. key_hash is irreversible and must not contain a raw visitor/session/email identifier.';

COMMIT;
