BEGIN;
CREATE TEMP TABLE _pta_seed (
 product_type_code text NOT NULL,
 attribute_code text NOT NULL,
 requirement_level text NOT NULL,
 value_level text NOT NULL,
 filterable boolean NOT NULL,
 searchable boolean NOT NULL,
 customer_visible boolean NOT NULL,
 comparable boolean NOT NULL,
 variant_defining boolean NOT NULL,
 allow_multiple boolean NOT NULL,
 sort_order integer NOT NULL,
 variant_axis_order integer,
 unit_override text,
 PRIMARY KEY(product_type_code,attribute_code)
) ON COMMIT DROP;
INSERT INTO _pta_seed VALUES
('beauty_care','skin_type','optional','family',true,true,true,true,false,false,40,NULL,NULL),
('haircare','hair_type','recommended','family',true,true,true,true,false,false,40,NULL,NULL),
('skincare','skin_type','recommended','family',true,true,true,true,false,false,40,NULL,NULL),
('sun_care','skin_type','optional','family',true,true,true,true,false,false,40,NULL,NULL),
('sun_care','spf','required','family',true,false,true,true,false,false,50,NULL,NULL),
('garden_supply','pot_diameter_cm','optional','variant',true,false,true,true,true,false,70,2,NULL),
('plant','pot_diameter_cm','recommended','variant',true,false,true,true,true,false,10,1,NULL),
('plant','manufacturer_variant','optional','variant',false,true,true,false,true,false,20,2,NULL),
('plant','product_dimensions','optional','family',false,false,true,true,false,false,30,NULL,NULL),
('heating_cooling_appliance','power_w','recommended','family',true,false,true,true,false,false,70,NULL,NULL),
('heating_cooling_appliance','energy_class','optional','family',true,true,true,true,false,false,80,NULL,NULL),
('heating_cooling_appliance','installation_type','optional','family',true,true,true,true,false,false,90,NULL,NULL),
('heating_cooling_appliance','noise_db','optional','family',true,false,true,true,false,false,100,NULL,NULL),
('heating_cooling_appliance','capacity_l','optional','family',true,false,true,true,false,false,110,NULL,NULL),
('heating_cooling_appliance','load_capacity_kg','optional','family',true,false,true,true,false,false,120,NULL,NULL),
('small_appliance','power_w','recommended','family',true,false,true,true,false,false,70,NULL,NULL),
('small_appliance','energy_class','optional','family',true,true,true,true,false,false,80,NULL,NULL),
('small_appliance','installation_type','optional','family',true,true,true,true,false,false,90,NULL,NULL),
('small_appliance','noise_db','optional','family',true,false,true,true,false,false,100,NULL,NULL),
('small_appliance','capacity_l','optional','family',true,false,true,true,false,false,110,NULL,NULL),
('small_appliance','load_capacity_kg','optional','family',true,false,true,true,false,false,120,NULL,NULL),
('large_appliance','power_w','recommended','family',true,false,true,true,false,false,70,NULL,NULL),
('large_appliance','energy_class','optional','family',true,true,true,true,false,false,80,NULL,NULL),
('large_appliance','installation_type','optional','family',true,true,true,true,false,false,90,NULL,NULL),
('large_appliance','noise_db','optional','family',true,false,true,true,false,false,100,NULL,NULL),
('large_appliance','capacity_l','optional','family',true,false,true,true,false,false,110,NULL,NULL),
('large_appliance','load_capacity_kg','optional','family',true,false,true,true,false,false,120,NULL,NULL),
('heating_cooling_appliance','power_source','recommended','family',true,true,true,true,false,false,130,NULL,NULL),
('home_textile','manufacturer_variant','optional','variant',false,true,true,false,true,false,70,2,NULL),
('home_decor','finish','optional','family',true,true,true,true,false,false,70,NULL,NULL),
('lighting_component','bulb_base','recommended','family',true,true,true,true,false,false,70,NULL,NULL),
('lighting_component','power_w','recommended','family',true,false,true,true,false,false,80,NULL,NULL),
('lighting_component','colour_temperature_k','optional','variant',true,false,true,true,true,false,90,2,NULL),
('lighting_component','luminous_flux_lm','optional','family',true,false,true,true,false,false,100,NULL,NULL),
('security_device','connectivity','recommended','family',true,true,true,true,false,true,70,NULL,NULL),
('security_device','protection_rating','optional','family',true,true,true,true,false,false,80,NULL,NULL),
('security_device','power_source','recommended','family',true,true,true,true,false,false,90,NULL,NULL),
('camera','camera_resolution_mp','recommended','family',true,false,true,true,false,false,70,NULL,NULL),
('camera','lens_mount','optional','family',true,true,true,true,false,false,80,NULL,NULL),
('camera','connectivity','optional','family',true,true,true,true,false,true,90,NULL,NULL),
('camera_lens','lens_mount','required','family',true,true,true,true,false,false,70,NULL,NULL),
('camera_lens','focal_length_mm','recommended','family',true,true,true,true,false,false,80,NULL,NULL),
('camera_accessory','compatibility','recommended','family',true,true,true,true,false,false,70,NULL,NULL),
('consumer_electronics','connectivity','recommended','family',true,true,true,true,false,true,70,NULL,NULL),
('consumer_electronics','battery_capacity_mah','optional','family',true,false,true,true,false,false,80,NULL,NULL),
('consumer_electronics','screen_size_inches','optional','variant',true,false,true,true,true,false,90,2,NULL),
('consumer_electronics','storage_capacity_gb','optional','variant',true,false,true,true,true,false,100,3,NULL),
('consumer_electronics','display_resolution','optional','family',true,true,true,true,false,false,110,NULL,NULL),
('mobile_accessory','compatibility','recommended','family',true,true,true,true,false,false,70,NULL,NULL),
('mobile_accessory','connector','optional','variant',true,true,true,true,true,false,80,2,NULL),
('mobile_accessory','power_w','optional','family',true,false,true,true,false,false,90,NULL,NULL),
('mobile_accessory','battery_capacity_mah','optional','variant',true,false,true,true,true,false,100,3,NULL),
('mobile_accessory','cable_length_m','optional','variant',true,false,true,true,true,false,110,4,NULL),
('computer_peripheral','connectivity','recommended','family',true,true,true,true,false,true,70,NULL,NULL),
('computer_peripheral','compatibility','optional','family',true,true,true,true,false,false,80,NULL,NULL),
('computer_storage','storage_capacity_gb','required','variant',true,false,true,true,true,false,30,1,NULL),
('computer_storage','storage_type','required','family',true,true,true,true,false,false,40,NULL,NULL),
('computer_storage','connectivity','optional','family',true,true,true,true,false,true,50,NULL,NULL),
('network_device','connectivity','recommended','family',true,true,true,true,false,true,50,NULL,NULL),
('network_device','wireless','optional','family',true,false,true,true,false,false,60,NULL,NULL),
('printer_scanner','connectivity','recommended','family',true,true,true,true,false,true,70,NULL,NULL),
('printer_scanner','wireless','optional','family',true,false,true,true,false,false,80,NULL,NULL),
('computer_component','compatibility','required','family',true,true,true,true,false,false,30,NULL,NULL),
('monitor','screen_size_inches','required','variant',true,false,true,true,true,false,70,2,NULL),
('monitor','display_resolution','recommended','family',true,true,true,true,false,false,80,NULL,NULL),
('monitor','refresh_rate_hz','recommended','family',true,false,true,true,false,false,90,NULL,NULL),
('monitor','panel_type','optional','family',true,true,true,true,false,false,100,NULL,NULL),
('desktop_computer','processor','required','variant',true,true,true,true,true,false,70,2,NULL),
('desktop_computer','ram_gb','required','variant',true,false,true,true,true,false,80,3,NULL),
('desktop_computer','storage_capacity_gb','required','variant',true,false,true,true,true,false,90,4,NULL),
('desktop_computer','storage_type','recommended','family',true,true,true,true,false,false,100,NULL,NULL),
('desktop_computer','operating_system','recommended','family',true,true,true,true,false,false,110,NULL,NULL),
('electrical_supply','voltage_v','optional','family',true,false,true,true,false,false,30,NULL,NULL),
('electrical_supply','compatibility','optional','family',true,true,true,true,false,false,40,NULL,NULL),
('electrical_supply','pack_quantity','optional','variant',true,false,true,true,true,false,50,1,NULL);

INSERT INTO product_type_attributes(
 product_type_id,attribute_id,requirement_level,value_level,filterable,searchable,
 customer_visible,comparable,variant_defining,allow_multiple,sort_order,variant_axis_order,unit_override,updated_at
)
SELECT pt.id,ad.id,s.requirement_level,s.value_level,s.filterable,s.searchable,
       s.customer_visible,s.comparable,s.variant_defining,s.allow_multiple,s.sort_order,s.variant_axis_order,s.unit_override,now()
FROM _pta_seed s
JOIN product_types pt ON pt.code=s.product_type_code
JOIN attribute_definitions ad ON ad.code=s.attribute_code AND ad.active=true
ON CONFLICT (product_type_id,attribute_id) DO UPDATE SET
 requirement_level=EXCLUDED.requirement_level,
 value_level=EXCLUDED.value_level,
 filterable=EXCLUDED.filterable,
 searchable=EXCLUDED.searchable,
 customer_visible=EXCLUDED.customer_visible,
 comparable=EXCLUDED.comparable,
 variant_defining=EXCLUDED.variant_defining,
 allow_multiple=EXCLUDED.allow_multiple,
 sort_order=EXCLUDED.sort_order,
 variant_axis_order=EXCLUDED.variant_axis_order,
 unit_override=EXCLUDED.unit_override,
 updated_at=now();
COMMIT;
