import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "../../components/SiteFooter";
import { SiteHeader } from "../../components/SiteHeader";

export const metadata: Metadata = {
  title: "Πληρωμές & ασφάλεια checkout",
  description: "Πώς λειτουργεί η ενιαία πληρωμή, η φιλοξενούμενη σελίδα Viva και η επαλήθευση παραγγελίας στο ΚΟΝΤΑ ΜΟΥ Sparta.",
  alternates: { canonical: "/payments-security" }
};

export default function PaymentsSecurityPage() {
  return <main>
    <div className="announcement">Μία πληρωμή · server-side σύνολα · επιβεβαίωση πριν ολοκληρωθεί η παραγγελία.</div>
    <SiteHeader compact />
    <section className="content-hero content-hero-payments"><div className="shell content-hero-grid"><div><div className="eyebrow light">Checkout με καθαρά όρια</div><h1>Η κάρτα σου δεν περνά από τις φόρμες του marketplace.</h1><p>Όταν η production σύνδεση είναι ενεργή, η πληρωμή ολοκληρώνεται στη φιλοξενούμενη εμπειρία Viva Smart Checkout. Το ΚΟΝΤΑ ΜΟΥ Sparta δημιουργεί και επαληθεύει την παραγγελία χωρίς να συλλέγει ή να αποθηκεύει στοιχεία κάρτας.</p><div className="hero-actions"><Link className="button button-light" href="/cart">Έλεγξε το καλάθι</Link><Link className="button content-outline" href="/checkout">Πήγαινε στο checkout</Link></div></div><div className="payment-shield" aria-hidden="true"><span><img src="/brand/kontamou-sparta-logo.webp" alt="" width={72} height={48} style={{ width: "72px", height: "48px", objectFit: "contain" }} /></span><strong>→ VIVA →</strong><small>VERIFIED ORDER</small></div></div></section>
    <section className="shell content-section"><div className="content-heading"><div><div className="eyebrow">Τι συμβαίνει όταν πληρώνεις</div><h2>Τέσσερα διακριτά στάδια.</h2></div><p>Η οθόνη του browser δεν αποφασίζει τιμή, διαθεσιμότητα ή τελική επιτυχία πληρωμής.</p></div><div className="process-list"><article><span>01</span><div><h3>Το backend ξαναυπολογίζει</h3><p>Το checkout στέλνει προϊόντα, ποσότητες και επιλογή εκπλήρωσης. Η υπηρεσία ελέγχει ξανά τιμές, απόθεμα και επιλέξιμο τρόπο παράδοσης.</p></div></article><article><span>02</span><div><h3>Δημιουργείται ασφαλής προσπάθεια</h3><p>Ένα idempotency key συνδέει την προσπάθεια με το συγκεκριμένο καλάθι ώστε η επανάληψη ή το refresh να μη δημιουργεί ανεξέλεγκτα διπλές αγορές.</p></div></article><article><span>03</span><div><h3>Μετάβαση στη Viva</h3><p>Στο production flow μεταφέρεσαι στο hosted Smart Checkout. Τα στοιχεία πληρωμής εισάγονται στο περιβάλλον του παρόχου, όχι σε πεδίο κάρτας του ΚΟΝΤΑ ΜΟΥ Sparta.</p></div></article><article><span>04</span><div><h3>Επαλήθευση και τελική κατάσταση</h3><p>Η επιστροφή του browser από μόνη της δεν αρκεί. Η πλατφόρμα επαληθεύει το payment event και μετά ενημερώνει την πραγματική κατάσταση παραγγελίας.</p></div></article></div></section>
    <section className="content-band"><div className="shell content-split"><div><div className="eyebrow light">Αν κάτι διακοπεί</div><h2>Μην επαναλαμβάνεις τυφλά την πληρωμή.</h2><p>Ένα κλειστό παράθυρο, timeout ή αργή επιστροφή δεν αποδεικνύουν ούτε επιτυχία ούτε αποτυχία. Έλεγξε πρώτα τον λογαριασμό και την κατάσταση παραγγελίας. Αν η αγορά δεν υπάρχει και το checkout παραμένει ενεργό, μπορείς να συνεχίσεις από το καλάθι.</p><Link className="button button-light" href="/account">Έλεγξε τις παραγγελίες</Link></div><div className="content-fact-list"><div><strong>Pending</strong><span>Η προσπάθεια περιμένει οριστική επιβεβαίωση· μην θεωρήσεις ότι ολοκληρώθηκε.</span></div><div><strong>Failed / cancelled</strong><span>Η παραγγελία δεν πρέπει να παρουσιάζεται ως πληρωμένη. Επανέλεγξε το καλάθι πριν νέα προσπάθεια.</span></div><div><strong>Verified</strong><span>Η παραγγελία εμφανίζεται στον λογαριασμό με server-side σύνολο και τις επόμενες καταστάσεις εκπλήρωσης.</span></div></div></div></section>
    <section className="shell content-section"><div className="content-heading"><div><div className="eyebrow">Τι προστατεύεται</div><h2>Ασφάλεια σε κάθε όριο.</h2></div><p>Οι μηχανισμοί λειτουργούν μαζί και δεν αντικαθιστούν την προσεκτική επιβεβαίωση στοιχείων από τον πελάτη.</p></div><div className="principle-grid"><article><span>PRICE</span><h3>Server-side totals</h3><p>Η τελική χρέωση δεν εμπιστεύεται ποσά που υπολογίστηκαν μόνο στον browser.</p></article><article><span>SESSION</span><h3>Προστατευμένες ενέργειες</h3><p>Authenticated μεταβολές χρησιμοποιούν session και CSRF controls, ενώ ευαίσθητα tokens δεν εκτίθενται στο UI.</p></article><article><span>STATUS</span><h3>Επαληθευμένα events</h3><p>Η επιτυχία βασίζεται σε επαληθευμένη ροή παρόχου και όχι μόνο σε ένα success URL.</p></article></div></section>
    <section className="shell content-cta"><div><div className="eyebrow">Πριν πληρώσεις</div><h2>Έλεγξε προϊόντα, ποσότητες και τρόπο παραλαβής.</h2><p>Η τελική διαθεσιμότητα και χρέωση επιβεβαιώνονται στο checkout.</p></div><div className="hero-actions"><Link className="button" href="/cart">Άνοιξε το καλάθι</Link><Link className="button button-secondary" href="/delivery-pickup">Δες την εκπλήρωση</Link></div></section>
    <SiteFooter />
  </main>;
}
