import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import "./storefront-merchants.css";
import "./storefront-advice.css";
import "./storefront-content.css";
import "./storefront-merchant-media.css";
import "./dashboard-ux.css";
import "./dashboard-premium.css";
import "./site-polish.css";
import "./workspace-polish.css";
import "./checkout-polish.css";
import "./dashboard-luxury.css";
import "./workspace-pages.css";
import "./workspace-metrics-polish.css";
import "./typography-readability.css";
import "./admin-information-architecture.css";
import "./admin-domain-workspaces.css";
import "./admin-directory-search.css";
import "./admin-orders-directory.css";
import "./admin-local-tabs.css";
import "./admin-partner-record.css";
import "./admin-matching-split.css";
import { CartProvider } from "../components/CartProvider";
import { publicOrigin } from "../lib/public-origin";
const comfortaa = Comfortaa({ subsets: ["greek", "latin"], display: "swap", variable: "--font-comfortaa" });
export const metadata: Metadata = { metadataBase: new URL(publicOrigin()), title: { default: "ΚΟΝΤΑ ΜΟΥ Sparta | Η τοπική αγορά της Σπάρτης online", template: "%s | ΚΟΝΤΑ ΜΟΥ Sparta" }, description: "Ανακάλυψε προϊόντα από καταστήματα της Σπάρτης, πάρε πραγματική συμβουλή από τοπικούς επαγγελματίες και αγόρασε με μία ενιαία εμπειρία checkout.", keywords: ["Σπάρτη", "τοπικά καταστήματα", "ΚΟΝΤΑ ΜΟΥ", "marketplace", "Λακωνία", "online αγορές"], openGraph: { title: "ΚΟΝΤΑ ΜΟΥ Sparta", description: "ΚΟΝΤΑ ΜΟΥ: Η Σπάρτη δίπλα σου", locale: "el_GR", type: "website", url: "/" } };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="el" className={comfortaa.variable}><body><CartProvider>{children}</CartProvider></body></html>; }
