import { createHash, randomUUID } from "node:crypto";
import { PostgresUnitOfWork, type SessionPrincipal, type SqlPool, type SqlRow } from "@buy-local-sparta/core";
import { AadeMyDataClient, type MyDataTransmissionResult } from "@buy-local-sparta/aade-mydata";
import { platformScope } from "./admin-auth.ts";

export type MyDataDocumentProjection = Readonly<{
  id:string; orderId?:string; type:string; status:string; transmissionStatus:string; grossMinor:number; currency:string;
  mappingVersion?:string; invoiceTypeCode?:string; documentNumber?:string; aadeMark?:string; aadeUid?:string; qrUrl?:string; lastError?:string; createdAt:number;
}>;

export class PostgresMyDataService {
  readonly #uow:PostgresUnitOfWork;
  readonly #client:AadeMyDataClient;
  readonly #issuanceEnabled:boolean;
  readonly #approvedMappingVersion?:string;
  constructor(pool:SqlPool,input:{client:AadeMyDataClient;issuanceEnabled:boolean;approvedMappingVersion?:string}){this.#uow=new PostgresUnitOfWork(pool);this.#client=input.client;this.#issuanceEnabled=input.issuanceEnabled;this.#approvedMappingVersion=input.approvedMappingVersion?.trim()||undefined;}

  async workspace(principal:SessionPrincipal):Promise<{environment:string;specVersion:string;issuanceEnabled:boolean;approvedMappingVersion?:string;documents:readonly MyDataDocumentProjection[]}>{
    const documents=await this.#uow.withTransaction(platformScope(principal.userId),async tx=>{const r=await tx.query<SqlRow>(`SELECT td.public_id,o.public_id AS order_public_id,td.type,td.status,td.transmission_status,td.gross_minor,td.currency,td.mapping_version,td.invoice_type_code,td.document_number,td.aade_mark,td.aade_uid,td.aade_qr_url,td.last_error,td.created_at FROM tax_documents td LEFT JOIN customer_orders o ON o.id=td.order_id ORDER BY td.created_at DESC LIMIT 250`);return r.rows.map(row=>({id:text(row.public_id),orderId:optional(row.order_public_id),type:text(row.type),status:text(row.status),transmissionStatus:text(row.transmission_status),grossMinor:int(row.gross_minor),currency:text(row.currency),mappingVersion:optional(row.mapping_version),invoiceTypeCode:optional(row.invoice_type_code),documentNumber:optional(row.document_number),aadeMark:optional(row.aade_mark),aadeUid:optional(row.aade_uid),qrUrl:optional(row.aade_qr_url),lastError:optional(row.last_error),createdAt:epoch(row.created_at)}))},{readOnly:true});
    return{environment:this.#client.environment,specVersion:this.#client.specVersion,issuanceEnabled:this.#issuanceEnabled,approvedMappingVersion:this.#approvedMappingVersion,documents};
  }

  async transmitPreparedDocument(principal:SessionPrincipal,input:{documentId:string;now?:number}):Promise<MyDataTransmissionResult>{
    if(!this.#issuanceEnabled)throw new Error("AADE myDATA issuance is disabled until the accounting mapping is approved");
    if(!this.#approvedMappingVersion)throw new Error("BLS_MYDATA_MAPPING_VERSION is required before issuance");
    const now=input.now??Date.now();
    const prepared=await this.#uow.withTransaction(platformScope(principal.userId),async tx=>{const r=await tx.query<SqlRow>(`SELECT id::text AS document_uuid,public_id,status,transmission_status,mapping_version,payload_snapshot,aade_mark FROM tax_documents WHERE public_id=$1 FOR UPDATE`,[input.documentId]);if(!r.rowCount)throw new Error("Tax document not found");const row=r.rows[0];if(optional(row.aade_mark))return{alreadyAccepted:true as const};if(text(row.mapping_version)!==this.#approvedMappingVersion)throw new Error("Tax document mapping version is not the approved production mapping");if(text(row.transmission_status)!=="ready")throw new Error(`Tax document is ${text(row.transmission_status)}, not ready for transmission`);const payload=json(row.payload_snapshot);const xml=typeof payload.mydataXml==="string"?payload.mydataXml.trim():"";if(!xml)throw new Error("Prepared tax document is missing accountant-approved myDATA XML");const hash=createHash("sha256").update(xml).digest("hex");const attemptKey=`send:${input.documentId}:${hash}`;const existing=await tx.query<SqlRow>(`SELECT status FROM mydata_transmission_attempts WHERE tax_document_id=$1 AND operation='send_invoice' AND attempt_key=$2`,[text(row.document_uuid),attemptKey]);if(existing.rowCount){const status=text(existing.rows[0].status);if(status==="accepted")return{alreadyAccepted:true as const};throw new Error(`Existing AADE transmission attempt is ${status}; reconcile it instead of retrying blindly`);}await tx.query(`INSERT INTO mydata_transmission_attempts(public_id,tax_document_id,operation,attempt_key,environment,spec_version,request_hash,status,started_at) VALUES($1,$2,'send_invoice',$3,$4,$5,$6,'started',$7)`,[`mda_${randomUUID().replaceAll("-","")}`,text(row.document_uuid),attemptKey,this.#client.environment,this.#client.specVersion,hash,new Date(now)]);await tx.query("UPDATE tax_documents SET transmission_status='transmitting',last_transmission_at=$2,last_error=NULL WHERE id=$1",[text(row.document_uuid),new Date(now)]);return{alreadyAccepted:false as const,documentUuid:text(row.document_uuid),attemptKey,xml};},{isolation:"serializable"});
    if(prepared.alreadyAccepted)return{ok:true,items:[],rawXml:""};
    let result:MyDataTransmissionResult;
    try{result=await this.#client.sendInvoices(prepared.xml);}catch(error){const message=error instanceof Error?error.message:String(error);await this.#uow.withTransaction(platformScope(principal.userId),async tx=>{await tx.query(`UPDATE mydata_transmission_attempts SET status='manual_review',http_summary=$3,completed_at=$4 WHERE tax_document_id=$1 AND attempt_key=$2`,[prepared.documentUuid,prepared.attemptKey,message.slice(0,1000),new Date(now)]);await tx.query(`UPDATE tax_documents SET transmission_status='manual_review',last_error=$2,last_transmission_at=$3 WHERE id=$1`,[prepared.documentUuid,message.slice(0,1000),new Date(now)]);});throw new Error("AADE myDATA outcome is uncertain; automatic retry is blocked pending reconciliation");}
    await this.#uow.withTransaction(platformScope(principal.userId),async tx=>{const first=result.items[0];const accepted=result.ok&&Boolean(first?.invoiceMark);const errors=result.items.flatMap(i=>i.errors.map(e=>e.code?`${e.code}: ${e.message}`:e.message)).join(" | ");await tx.query(`UPDATE mydata_transmission_attempts SET status=$3,response_snapshot=$4::jsonb,completed_at=$5 WHERE tax_document_id=$1 AND attempt_key=$2`,[prepared.documentUuid,prepared.attemptKey,accepted?"accepted":"rejected",JSON.stringify({ok:result.ok,items:result.items}),new Date(now)]);await tx.query(`UPDATE tax_documents SET transmission_status=$2,status=$3,aade_mark=$4,aade_uid=$5,aade_qr_url=$6,provider='aade_mydata_erp',provider_document_id=COALESCE($4,provider_document_id),last_error=$7,last_transmission_at=$8,issued_at=CASE WHEN $2='accepted' THEN COALESCE(issued_at,$8) ELSE issued_at END WHERE id=$1`,[prepared.documentUuid,accepted?"accepted":"rejected",accepted?"issued":"rejected",first?.invoiceMark??null,first?.invoiceUid??null,first?.qrUrl??null,errors||null,new Date(now)]);},{isolation:"serializable"});
    return result;
  }
}
function text(v:unknown):string{if(typeof v!=="string"||!v)throw new Error("Invalid database text");return v}function optional(v:unknown):string|undefined{return typeof v==="string"&&v? v:undefined}function int(v:unknown):number{const n=Number(v);if(!Number.isSafeInteger(n))throw new Error("Invalid database integer");return n}function epoch(v:unknown):number{const n=v instanceof Date?v.getTime():new Date(String(v)).getTime();if(!Number.isFinite(n))throw new Error("Invalid database timestamp");return n}function json(v:unknown):Record<string,unknown>{if(v&&typeof v==="object"&&!Array.isArray(v))return v as Record<string,unknown>;if(typeof v==="string")try{const p=JSON.parse(v);return p&&typeof p==="object"&&!Array.isArray(p)?p:{};}catch{return{}}return{}}
