import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AdminWorkspaceHeader } from "../../../components/AdminWorkspaceHeader";
import { WorkspaceMetricStrip, WorkspaceSectionHeading } from "../../../components/WorkspacePagePrimitives";
import { adminVendorsWorkspace, hasAdminPermission } from "../../../lib/admin-runtime";
import { getAdminSession } from "../../../lib/admin-session";
import { verifiedProspectsWorkspace } from "../../../lib/prospect-vendors-runtime";
import { researchVendorsWorkspace } from "../../../lib/research-vendors-runtime";
import { adminVendorShopsWorkspace } from "../../../lib/vendor-admin-controls";

export const metadata: Metadata = { title: "Admin · Partners", robots: { index: false, follow: false } };

export default async function Page() {
  const principal = await getAdminSession(); if (!principal) redirect("/admin/login"); if (!hasAdminPermission(principal, "vendor.manage")) redirect("/admin");
  const [research, applications, prospects, managed] = await Promise.all([researchVendorsWorkspace(principal), adminVendorsWorkspace(principal), verifiedProspectsWorkspace(principal), adminVendorShopsWorkspace(principal)]);
  const pendingApplications = applications.applications.filter((item) => !item.vendorId).length; const active = managed.shops.filter((shop) => shop.operationalActive).length; const visible = managed.shops.filter((shop) => shop.operationalActive && shop.publicDirectoryVisible).length; const missingAgreement = managed.shops.filter((shop) => !shop.cooperationDocumented).length;
  return <main className="vendor-app admin-app"><AdminWorkspaceHeader csrfToken={applications.csrfToken} /><section className="shell vendor-hero vendor-hero-compact dashboard-hero-refined"><div><div className="eyebrow">Partners</div><h1>Συνεργάτες</h1><p className="lead">Acquisition, onboarding, ενεργά καταστήματα και εμπορικές συμφωνίες ως ένα ενιαίο partner lifecycle.</p></div></section><WorkspaceMetricStrip items={[{ label: "Research leads", value: research.summary.total },{ label: "Pending applications", value: pendingApplications, tone: pendingApplications ? "attention" : "default" },{ label: "Active partners", value: active, tone: active ? "positive" : "default", hint: `${visible} publicly visible` },{ label: "Agreement gaps", value: missingAgreement, tone: missingAgreement ? "attention" : "positive", hint: `${prospects.summary.total} in onboarding` }]} /><section className="shell vendor-section"><WorkspaceSectionHeading eyebrow="Partner lifecycle" title="Ένα domain αντί για διάσπαρτες vendor οθόνες" note="Οι υπάρχουσες governed ενέργειες παραμένουν εκεί που είναι σήμερα· αυτή η επιφάνεια οργανώνει το lifecycle και δίνει ένα σταθερό σημείο εισόδου." /><div className="admin-domain-card-grid"><Link className="admin-domain-card" href="/admin/vendors"><span>Directory</span><strong>Κατάλογος συνεργατών</strong><p>Operational status, public visibility, locations και partner-level controls.</p><b>{managed.shops.length}</b><i>Άνοιγμα →</i></Link><Link className={`admin-domain-card${pendingApplications || prospects.summary.total ? " needs-attention" : ""}`} href="/admin/partners/pipeline"><span>Pipeline</span><strong>Acquisition & onboarding</strong><p>Lead → application → verification → contract → catalog → test → active.</p><b>{pendingApplications + prospects.summary.total}</b><i>Pipeline →</i></Link>{hasAdminPermission(principal, "finance.read") && <Link className={`admin-domain-card${missingAgreement ? " needs-attention" : ""}`} href="/admin/finance/agreements"><span>Commercial</span><strong>Συμφωνίες</strong><p>Commercial terms, signed evidence και agreement lifecycle ανά συνεργάτη.</p><b>{missingAgreement}</b><i>Συμφωνίες →</i></Link>}{hasAdminPermission(principal, "finance.read") && <Link className="admin-domain-card" href="/admin/finance/agreements/sla"><span>Service levels</span><strong>SLA συμφωνιών</strong><p>Vendor-specific acceptance / preparation policies που τροφοδοτούν το operational SLA engine.</p><b>SLA</b><i>Policies →</i></Link>}</div></section></main>;
}
