"use client";
import { useState } from "react";
import type { AskLocalRequestView } from "../lib/ask-local-service";
type Context = Readonly<{ need?: string; canonicalVariantId?: string; preferredVendorId?: string; sourceUrl?: string }>;
const labels: Record<string, string> = { submitted: "Σε έλεγχο από την πλατφόρμα", assigned: "Ανατέθηκε ιδιωτικά", awaiting_vendor: "Αναμονή απάντησης καταστήματος", needs_info: "Χρειάζονται πληροφορίες", offered: "Έχει σταλεί ιδιωτική προσφορά", accepted: "Αποδεκτή προσφορά", converted: "Μετατράπηκε σε αγορά", declined: "Απορρίφθηκε", expired: "Έληξε", closed: "Ολοκληρώθηκε" };
const date = (value: number) => new Intl.DateTimeFormat("el-GR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
export function AskLocalClient({ csrfToken, initial, context }: { csrfToken: string; initial: readonly AskLocalRequestView[]; context: Context }) {
  const [requests, setRequests] = useState(initial),[busy, setBusy] = useState(false),[error, setError] = useState(""),[success, setSuccess] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; setBusy(true); setError(""); setSuccess(""); const form = new FormData(formElement); try { const response = await fetch("/api/account/ask-local", { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": csrfToken }, body: JSON.stringify({ need: form.get("need"), postcode: form.get("postcode"), quantity: Number(form.get("quantity")), sourceUrl: form.get("sourceUrl"), canonicalVariantId: context.canonicalVariantId, preferredVendorId: context.preferredVendorId, category: form.get("category") }) }); const payload = await response.json() as { request?: AskLocalRequestView; error?: string }; if (!response.ok || !payload.request) throw new Error(payload.error ?? "Το αίτημα δεν ολοκληρώθηκε"); setRequests((current) => [payload.request!, ...current]); setSuccess(`Το αίτημα ${payload.request.id} καταχωρίστηκε ιδιωτικά.`); formElement.reset(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Το αίτημα δεν ολοκληρώθηκε"); } finally { setBusy(false); } }
  return <><section className="shell ask-local-workspace"><form className="ask-local-live-form" onSubmit={submit}><div className="ask-local-full"><div className="eyebrow">Νέο ιδιωτικό αίτημα</div><h2>Τι ψάχνεις;</h2><p>Περιέγραψε προϊόν, χρήση, budget ή συμβουλή. Δεν δημοσιεύεται σε πολλούς vendors.</p></div><label className="ask-local-full"><span>Περιγραφή</span><textarea name="need" minLength={10} maxLength={2000} required defaultValue={context.need} placeholder="π.χ. Θέλω δώρο για παιδί 8 ετών, έως 35€." /></label><label><span>Ταχυδρομικός κώδικας</span><input name="postcode" inputMode="numeric" pattern="[0-9]{5}" maxLength={5} defaultValue="23100" required /></label><label><span>Ποσότητα</span><input name="quantity" type="number" min={1} max={99} defaultValue={1} required /></label><label><span>Κατηγορία (προαιρετικά)</span><input name="category" maxLength={100} placeholder="π.χ. παιχνίδι" /></label><label><span>Σύνδεσμος αναφοράς</span><input name="sourceUrl" type="url" maxLength={2000} defaultValue={context.sourceUrl} placeholder="https://…" /></label>{context.canonicalVariantId && <div className="ask-local-context">Συνδεδεμένο προϊόν: <strong>{context.canonicalVariantId}</strong></div>}{context.preferredVendorId && !context.canonicalVariantId && <div className="ask-local-context">Επιλεγμένο κατάστημα: <strong>{context.preferredVendorId}</strong></div>}{error && <div className="form-error ask-local-full" role="alert">{error}</div>}{success && <div className="checkout-result success ask-local-full" role="status">{success}</div>}<button className="button ask-local-submit" disabled={busy} type="submit">{busy ? "Αποστολή…" : "Αποστολή ιδιωτικού αιτήματος"}</button></form></section>
    <section className="shell section" aria-labelledby="requests-title"><div className="section-heading"><div><div className="eyebrow">Τα αιτήματά μου</div><h2 id="requests-title">Ιδιωτική εξέλιξη</h2></div><p className="section-note">Η ανάθεση και οι προσφορές εμφανίζονται μόνο στον λογαριασμό σου.</p></div>{requests.length ? <div className="ask-request-list">{requests.map((request) => <article className="ask-request-card" key={request.id}><div className="ask-request-head"><div><strong>{request.id}</strong><small>{date(request.createdAt)}</small></div><span className="status-pill">{labels[request.status] ?? request.status}</span></div><p>{request.need}</p><div className="ask-request-meta"><span>{request.quantity} τεμ.</span><span>ΤΚ {request.postcode}</span>{request.assignedVendorName && <span>Ιδιωτικά προς {request.assignedVendorName}</span>}{request.responseDueAt && <span>Απάντηση έως {date(request.responseDueAt)}</span>}</div>{request.privateOffers.length > 0 && <div className="private-offer-list">{request.privateOffers.map((offer) => <div key={offer.id}><strong>{new Intl.NumberFormat("el-GR", { style: "currency", currency: offer.currency }).format(offer.priceMinor / 100)}</strong><span>{offer.fulfilmentPromise ?? "Ιδιωτική προσφορά"}</span><small>{labels[offer.status] ?? offer.status} · έως {date(offer.expiresAt)}</small></div>)}</div>}</article>)}</div> : <div className="empty-state"><h2>Δεν έχεις ακόμη Ask Local αιτήματα.</h2><p>Το πρώτο σου αίτημα θα εμφανιστεί εδώ με την ιδιωτική του κατάσταση.</p></div>}</section></>;
}
