"use client";

import QRCode from "react-qr-code";
import { useState } from "react";
import type { DeliveryJobView } from "../lib/delivery-driver-runtime";
import { QrScannerOverlay } from "./QrScannerOverlay";
import styles from "./DeliveryOperations.module.css";

export function VendorDeliveryWorkspaceClient({ jobs, csrfToken }: { jobs: readonly DeliveryJobView[]; csrfToken: string }) {
  const [scanner,setScanner]=useState(false),[manual,setManual]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  async function confirm(value:string){if(!value.trim())return;setScanner(false);setBusy(true);setNotice("");try{const response=await fetch("/api/daily/delivery",{method:"POST",headers:{"content-type":"application/json","x-csrf-token":csrfToken},body:JSON.stringify({token:value.trim()})});const body=await response.json() as {error?:string;progress?:{done:number;total:number}};if(!response.ok)throw new Error(body.error??"Η επιβεβαίωση απέτυχε.");setNotice(body.progress?`Παραλαβή επιβεβαιώθηκε · ${body.progress.done}/${body.progress.total} σημεία.`:"Η επιβεβαίωση ολοκληρώθηκε.");setManual("");window.setTimeout(()=>window.location.reload(),500);}catch(error){setNotice(error instanceof Error?error.message:"Η επιβεβαίωση απέτυχε.");}finally{setBusy(false);}}
  const returnStops=jobs.flatMap((job)=>job.stops.filter((stop)=>stop.receiptQr).map((stop)=>({job,stop})));
  return <div className={styles.grid}>{notice&&<div className={styles.notice}>{notice}</div>}<section className={styles.card}><div className={styles.eyebrow}>Παραλαβές οδηγού</div><h2>Σκάναρε το κοινό QR του οδηγού</h2><p className={styles.muted}>Για παραγγελία με πολλά καταστήματα, ο οδηγός δείχνει το ίδιο QR παντού. Η σάρωση ολοκληρώνει μόνο τη δική σου παραλαβή.</p><div className={styles.toolbar}><button className={styles.button} type="button" onClick={()=>setScanner(true)}>Άνοιγμα κάμερας</button></div><div className={styles.manual}><input value={manual} onChange={(event)=>setManual(event.target.value)} placeholder="Κωδικός QR οδηγού"/><button className={styles.buttonSecondary} type="button" disabled={busy||!manual.trim()} onClick={()=>void confirm(manual)}>Επιβεβαίωση</button></div></section><section><div className={styles.sectionTitle}><div><div className={styles.eyebrow}>Returns</div><h2>QR παραλαβής επιστροφών</h2></div></div>{returnStops.length===0?<div className={styles.empty}>Δεν υπάρχουν επιστροφές προς παραλαβή αυτή τη στιγμή.</div>:<div className={`${styles.grid} ${styles.two}`}>{returnStops.map(({job,stop})=><article className={styles.card} key={stop.id}><span className={styles.badge}>Επιστροφή · {job.orderId}</span><h3>{stop.vendorName||"Κατάστημα"}</h3><p className={styles.muted}>Όταν ο οδηγός φέρει την επιστροφή, δείξε του αυτό το QR. Ο οδηγός το σαρώνει για να κλείσει το συγκεκριμένο drop-off.</p><div className={styles.qrWrap}><QRCode value={stop.receiptQr!} size={220}/><small>Αναμονή παράδοσης</small></div></article>)}</div>}</section>{scanner&&<QrScannerOverlay onScan={(value)=>void confirm(value)} onClose={()=>setScanner(false)}/>}</div>;
}
