"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Workspace = { csrfToken:string; vendorId:string; csvTemplate:string; submissions:ReadonlyArray<{id:string;vendorSku?:string;title:string;categoryCode:string;status:string;canonicalVariantId?:string;supplierPrice:string;stockOnHand:number;fulfilmentModes:readonly string[];adviceAvailable:boolean;rejectionReason?:string;updatedAt:number;candidates:ReadonlyArray<{id:string;canonicalVariantId:string;canonicalTitle:string;level:string;confidence:number;status:string}>}> };
const when=(n:number)=>new Intl.DateTimeFormat("el-GR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(n));
export function VendorCatalogClient({initial}:{initial:Workspace}){const router=useRouter();const[busy,setBusy]=useState("");const[error,setError]=useState("");const[preview,setPreview]=useState<{totalRows:number;rows:readonly unknown[];errors:readonly {rowNumber:number;field?:string;message:string}[]}|null>(null);const[csv,setCsv]=useState(`${initial.csvTemplate}\nSKU-001,technology,Demo product,Demo Brand,Model X,,1000,5,1,pickup,true,colour=black`);
async function call(key:string,url:string,body:unknown){setBusy(key);setError("");try{const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json","x-csrf-token":initial.csrfToken},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p.error??"Η ενέργεια απέτυχε");if(p.preview)setPreview(p.preview);router.refresh();return p}catch(e){setError(e instanceof Error?e.message:"Η ενέργεια απέτυχε")}finally{setBusy("")}}
return <>
{error&&<div className="shell form-error vendor-error" role="alert">{error}</div>}
<section className="shell vendor-section"><div className="section-heading"><div><div className="eyebrow">Manual source product</div><h2>Νέο προϊόν</h2></div><p className="section-note">Η δημιουργία είναι draft. Η υποβολή ενεργοποιεί matching· δεν δημοσιεύει αυτόματα νέο canonical product.</p></div><form className="vendor-inline-form" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);void call("create","/api/vendor/catalog/products",{title:f.get("title"),categoryCode:f.get("category"),vendorSku:f.get("sku"),brand:f.get("brand"),supplierUnitPriceMinor:Number(f.get("price")),stockOnHand:Number(f.get("stock")),safetyStock:Number(f.get("safety"))})}}><input name="title" required placeholder="Τίτλος προϊόντος"/><input name="category" required placeholder="category code"/><input name="sku" placeholder="SKU"/><input name="brand" placeholder="Brand"/><input name="price" required type="number" min="0" step="1" placeholder="Supplier € cents"/><input name="stock" required type="number" min="0" step="1" placeholder="Stock"/><input name="safety" type="number" min="0" step="1" defaultValue="0" placeholder="Safety"/><button className="button" disabled={busy==="create"}>Αποθήκευση draft</button></form></section>
<section className="vendor-section section-tint"><div className="shell"><div className="section-heading"><div><div className="eyebrow">CSV import</div><h2>Dry-run → Confirm</h2></div></div><textarea className="vendor-csv" value={csv} onChange={(e)=>setCsv(e.target.value)} aria-label="CSV import"/><div className="vendor-toolbar-actions"><button className="button button-secondary" onClick={()=>void call("preview","/api/vendor/catalog/import",{csv,confirm:false})} disabled={!!busy}>Dry-run</button><button className="button" onClick={()=>void call("commit","/api/vendor/catalog/import",{csv,confirm:true})} disabled={!!busy||Boolean(preview?.errors.length)}>Confirm import</button></div>{preview&&<div className="vendor-preview"><strong>{preview.totalRows} rows · {preview.errors.length} errors</strong>{preview.errors.map((e,i)=><span key={i}>Row {e.rowNumber}{e.field?` · ${e.field}`:""}: {e.message}</span>)}</div>}</div></section>
<section className="shell vendor-section"><div className="section-heading"><div><div className="eyebrow">Product Matching Centre handoff</div><h2>Source products</h2></div></div><div className="vendor-order-list">{initial.submissions.map((item)=><article className="vendor-order" key={item.id}><div className="vendor-order-head"><div><strong>{item.title}</strong><small>{item.vendorSku??item.id} · {item.categoryCode} · {when(item.updatedAt)}</small></div><span className="status-pill">{item.status}</span></div><div className="vendor-order-lines"><span>Supplier price {item.supplierPrice} · stock {item.stockOnHand}</span>{item.canonicalVariantId&&<span>Linked canonical: <strong>{item.canonicalVariantId}</strong></span>}{item.candidates.map(c=><span key={c.id}>Candidate: {c.canonicalTitle} · {c.level} · {(c.confidence*100).toFixed(0)}% · {c.status}</span>)}{item.rejectionReason&&<span>Reason: {item.rejectionReason}</span>}</div><div className="vendor-order-foot"><span>Final match/offer approval is platform-controlled.</span>{["draft","needs_review","linked","rejected"].includes(item.status)&&<button className="button" disabled={!!busy} onClick={()=>void call(`submit:${item.id}`,`/api/vendor/catalog/products/${item.id}/submit`,{})}>Υποβολή</button>}</div></article>)}{!initial.submissions.length&&<div className="account-empty">Δεν υπάρχουν source products.</div>}</div></section>
</>}
