import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AdminWorkspaceHeader } from "../../../../components/AdminWorkspaceHeader";
import { WorkspaceMetricStrip, WorkspaceSectionHeading } from "../../../../components/WorkspacePagePrimitives";
import { adminVendorsWorkspace, hasAdminPermission } from "../../../../lib/admin-runtime";
import { getAdminSession } from "../../../../lib/admin-session";
import { verifiedProspectsWorkspace } from "../../../../lib/prospect-vendors-runtime";
import { researchVendorsWorkspace } from "../../../../lib/research-vendors-runtime";

export const metadata: Metadata = { title: "Admin · Partner Pipeline", robots: { index: false, follow: false } };

export default async function Page() {
  const principal = await getAdminSession(); if (!principal) redirect("/admin/login"); if (!hasAdminPermission(principal, "vendor.manage")) redirect("/admin");
  const [research, applications, prospects] = await Promise.all([researchVendorsWorkspace(principal), adminVendorsWorkspace(principal), verifiedProspectsWorkspace(principal)]);
  const pendingApplications = applications.applications.filter((item) => !item.vendorId).length; const verification = applications.applications.filter((item) => !item.vendorId && item.state === "verification_pending").length; const onboarding = prospects.summary.catalog; const testReady = prospects.summary.testReady;
  const stages = [{ label: "Research leads", value: research.summary.total, detail: `${research.summary.invited} invited`, href: "/admin/research-vendors" },{ label: "Applications", value: pendingApplications, detail: `${verification} verification pending`, href: "/admin/vendors" },{ label: "Onboarding", value: prospects.summary.total, detail: `${onboarding} catalog onboarding`, href: "/admin/prospects" },{ label: "Test ready", value: testReady, detail: `${prospects.summary.contractReady} contract ready`, href: "/admin/prospects" },{ label: "Active", value: research.summary.active, detail: "operational partners", href: "/admin/vendors" }];
  return <main className="vendor-app admin-app"><AdminWorkspaceHeader csrfToken={applications.csrfToken} /><section className="shell vendor-hero vendor-hero-compact dashboard-hero-refined"><div><div className="eyebrow">Partners · lifecycle</div><h1>Partner Pipeline</h1><p className="lead">Μία ενιαία διαδρομή από research lead μέχρι ενεργό συνεργάτη. Τα υπάρχοντα governed workflows παραμένουν τα source-of-truth για κάθε στάδιο.</p></div></section><WorkspaceMetricStrip items={[{ label: "Research leads", value: research.summary.total },{ label: "Pending applications", value: pendingApplications, tone: pendingApplications ? "attention" : "default" },{ label: "Verified prospects", value: prospects.summary.total },{ label: "Activation ready", value: testReady, tone: testReady ? "positive" : "default" }]} /><section className="shell vendor-section"><WorkspaceSectionHeading eyebrow="Lifecycle" title="Lead → Application → Verification → Onboarding → Active" note="Δεν αλλάζουμε τα audit gates. Αλλάζουμε τον τρόπο που ο Admin αντιλαμβάνεται και βρίσκει το workflow." /><div className="admin-pipeline">{stages.map((stage, index) => <Link href={stage.href} className="admin-pipeline-stage" key={stage.label}><span>{String(index + 1).padStart(2, "0")}</span><strong>{stage.label}</strong><b>{stage.value}</b><small>{stage.detail}</small><i aria-hidden="true">→</i></Link>)}</div></section><section className="shell vendor-section"><WorkspaceSectionHeading eyebrow="Next decisions" title="Onboarding που χρειάζεται συνέχεια" note="Οι verified prospects εμφανίζονται εδώ ως ενιαία pipeline preview. Οι πλήρεις governed actions παραμένουν στο αντίστοιχο record." />{prospects.prospects.length === 0 ? <div className="workspace-empty-state"><strong>Δεν υπάρχουν verified prospects.</strong><span>Οι νέες αιτήσεις θα εμφανιστούν μετά το Pass verification.</span></div> : <div className="admin-compact-table" role="table" aria-label="Partner onboarding preview"><div className="admin-compact-table-head" role="row"><span>Συνεργάτης</span><span>Στάδιο</span><span>Agreement</span><span>Επόμενο</span></div>{prospects.prospects.slice(0, 12).map((prospect) => <Link href="/admin/prospects" className="admin-compact-table-row" role="row" key={prospect.applicationId}><span><strong>{prospect.tradingName}</strong><small>{prospect.legalName}</small></span><span>{prospect.applicationState.replaceAll("_", " ")}</span><span>{prospect.agreementReady ? "Ready" : "Required"}</span><span>Άνοιγμα →</span></Link>)}</div>}</section></main>;
}
