import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AdminWorkspaceHeader } from "../../../components/AdminWorkspaceHeader";
import { WorkspaceMetricStrip, WorkspaceSectionHeading } from "../../../components/WorkspacePagePrimitives";
import { adminActivationWorkspace, adminOperationsWorkspace, hasAdminPermission } from "../../../lib/admin-runtime";
import { adminMaintenanceWorkspace } from "../../../lib/admin-governance-runtime";
import { getAdminSession } from "../../../lib/admin-session";
import { boxNowShippingEnabled } from "../../../lib/boxnow-shipping-runtime";
import { WEB_BUILD_VERSION } from "../../../lib/build";

export const metadata: Metadata = { title: "Admin · Platform", robots: { index: false, follow: false } };

export default async function Page() {
  const principal = await getAdminSession(); if (!principal) redirect("/admin/login"); if (!hasAdminPermission(principal, "admin.audit.read")) redirect("/admin");
  const [operations, maintenance, activation] = await Promise.all([adminOperationsWorkspace(principal), adminMaintenanceWorkspace(principal), adminActivationWorkspace(principal)]);
  const now = Date.now(); const criticalIssues = operations.health.checks.filter((check) => check.critical && !["ready", "healthy", "ok"].includes(String(check.state).toLowerCase())).length; const failingJobs = maintenance.jobNames.filter((job) => (job.state?.consecutiveFailures ?? 0) > 0).length; const currentBuild = activation.evidence.filter((row) => row.buildVersion === WEB_BUILD_VERSION); const currentFailed = currentBuild.filter((row) => row.status !== "passed" || Boolean(row.expiresAt && row.expiresAt <= now)).length; const boxNow = boxNowShippingEnabled();
  return <main className="vendor-app admin-app"><AdminWorkspaceHeader csrfToken={operations.csrfToken} /><section className="shell vendor-hero vendor-hero-compact dashboard-hero-refined"><div><div className="eyebrow">Platform</div><h1>Platform Control</h1><p className="lead">System health, integrations, jobs και launch readiness χωρισμένα από τις καθημερινές business operations.</p></div></section><WorkspaceMetricStrip items={[{ label: "Critical issues", value: criticalIssues, tone: criticalIssues ? "attention" : "positive" },{ label: "Security events · 24h", value: operations.security.summary.total },{ label: "Failing jobs", value: failingJobs, tone: failingJobs ? "attention" : "positive" },{ label: "Launch evidence issues", value: currentFailed, tone: currentFailed ? "attention" : "positive", hint: `build ${WEB_BUILD_VERSION}` }]} /><section className="shell vendor-section"><WorkspaceSectionHeading eyebrow="Platform domains" title="Τεχνική λειτουργία χωρίς σύγχυση με το marketplace ops" note="Οι integrations και launch gates είναι configuration/engineering εργαλεία και δεν εμφανίζονται πλέον δίπλα στις Orders ως ισότιμες καθημερινές ουρές." /><div className="admin-domain-card-grid"><Link className={`admin-domain-card${criticalIssues ? " needs-attention" : ""}`} href="/admin/operations"><span>Health</span><strong>System Health & Audit</strong><p>Dependencies, security telemetry και audit trail.</p><b>{criticalIssues}</b><i>Άνοιγμα →</i></Link><Link className="admin-domain-card" href="/admin/shipping"><span>Integration</span><strong>BOX NOW</strong><p>Courier provider configuration και fulfilment origin mapping.</p><b>{boxNow ? "ON" : "OFF"}</b><i>Ρυθμίσεις →</i></Link><Link className={`admin-domain-card${failingJobs ? " needs-attention" : ""}`} href="/admin/maintenance"><span>Runtime</span><strong>Jobs</strong><p>Scheduler, failures και canonical search projection.</p><b>{failingJobs}</b><i>Άνοιγμα →</i></Link><Link className={`admin-domain-card${currentFailed ? " needs-attention" : ""}`} href="/admin/activation"><span>Release</span><strong>Launch Readiness</strong><p>Current-build provider evidence και production gates.</p><b>{currentFailed}</b><i>Άνοιγμα →</i></Link></div></section></main>;
}
