import type { CategoryCommerceMode, ContentPageType, ReviewStatus, SessionPrincipal } from "@buy-local-sparta/core";
import * as memory from "./admin-governance-memory";
import { assertAdminPermission, hasAdminPermission, postgresAdminRuntimeEnabled } from "./admin-runtime";
import { getProductionPostgresRuntime } from "./postgres-runtime";

export function getAdminGovernanceRuntime(){return memory.getAdminGovernanceRuntime();}
export async function adminOrdersReturnsWorkspace(p:SessionPrincipal):Promise<ReturnType<typeof memory.adminOrdersReturnsWorkspace>>{assertAdminPermission(p,"fulfilment.read");if(postgresAdminRuntimeEnabled())return await getProductionPostgresRuntime().adminGovernance.ordersReturnsWorkspace(p) as ReturnType<typeof memory.adminOrdersReturnsWorkspace>;return memory.adminOrdersReturnsWorkspace(p);}
export async function adminCancelOrder(p:SessionPrincipal,input:{orderId:string;reason:string}){if(!hasAdminPermission(p,"returns.manage")&&!hasAdminPermission(p,"fulfilment.write"))throw new Error("Admin permission required: returns.manage or fulfilment.write");if(postgresAdminRuntimeEnabled()){const runtime=getProductionPostgresRuntime();if(runtime.vivaPayments)await runtime.vivaPayments.prepareOrderCancellation({orderId:input.orderId,reason:input.reason});return runtime.adminGovernance.cancelOrder(p,input);}return memory.adminCancelOrder(p,input);}
export async function adminReturnAction(p:SessionPrincipal,input:{returnId:string;action:"approve"|"authorize"|"receive"|"inspect_sellable"|"inspect_blocked"|"approve_refund"|"refund"|"reject";reason?:string}){assertAdminPermission(p,"returns.manage");if(postgresAdminRuntimeEnabled()){const runtime=getProductionPostgresRuntime();if(input.action==="refund"){if(!runtime.vivaPayments)throw new Error("Executing customer refunds requires configured Viva payments");return runtime.vivaPayments.executeApprovedReturnRefund({returnId:input.returnId,actorUserId:p.userId});}return runtime.adminGovernance.returnAction(p,input);}return memory.adminReturnAction(p,input);}
export async function adminReviewsWorkspace(p:SessionPrincipal){assertAdminPermission(p,"reviews.read");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.reviewsWorkspace(p);return memory.adminReviewsWorkspace(p);}
export async function adminModerateReview(p:SessionPrincipal,input:{reviewId:string;status:ReviewStatus;reason:string}){assertAdminPermission(p,"reviews.manage");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.moderateReview(p,input as any);return memory.adminModerateReview(p,input);}
export async function adminReviewReportAction(p:SessionPrincipal,input:{reportId:string;status:"under_review"|"resolved"|"rejected";resolution?:string}){assertAdminPermission(p,"reviews.manage");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.reviewReportAction(p,input);return memory.adminReviewReportAction(p,input);}
export async function adminPrivacyWorkspace(p:SessionPrincipal){assertAdminPermission(p,"privacy.read");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.privacyWorkspace(p);return memory.adminPrivacyWorkspace(p);}
export async function adminPrivacyAction(p:SessionPrincipal,input:{requestId:string;action:"start"|"complete"|"partial"}){assertAdminPermission(p,"privacy.manage");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.privacyAction(p,input);return memory.adminPrivacyAction(p,input);}
export async function adminCategoryWorkspace(p:SessionPrincipal){assertAdminPermission(p,"catalog.read");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.categoryWorkspace(p);return memory.adminCategoryWorkspace(p);}
export async function adminUpsertCategory(p:SessionPrincipal,input:{categoryCode:string;labelEl:string;commerceMode:CategoryCommerceMode}){assertAdminPermission(p,"catalog.write");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.upsertCategory(p,input);return memory.adminUpsertCategory(p,input);}
export async function adminContentWorkspace(p:SessionPrincipal){assertAdminPermission(p,"content.read");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.contentWorkspace(p);return memory.adminContentWorkspace(p);}
export async function adminCreateContentPage(p:SessionPrincipal,input:{slug:string;title:string;description:string;pageType?:ContentPageType}){assertAdminPermission(p,"content.write");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.createContentPage(p,input);return memory.adminCreateContentPage(p,input);}
export async function adminContentAction(p:SessionPrincipal,input:{pageId:string;action:"publish"|"archive"|"restore";reason?:string}){assertAdminPermission(p,"content.write");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.contentAction(p,input);return memory.adminContentAction(p,input);}
export async function adminRecallWorkspace(p:SessionPrincipal){assertAdminPermission(p,"returns.read");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.recallWorkspace(p);return memory.adminRecallWorkspace(p);}
export async function adminOpenRecall(p:SessionPrincipal,input:{canonicalVariantId:string;details:string;severity:"low"|"medium"|"high"|"critical"}){assertAdminPermission(p,"returns.manage");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.openRecall(p,input);return memory.adminOpenRecall(p,input);}
export async function adminResolveRecall(p:SessionPrincipal,input:{noticeId:string;resolution:string;restoreProduct?:boolean}){assertAdminPermission(p,"returns.manage");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.resolveRecall(p,input);return memory.adminResolveRecall(p,input);}
export async function adminMarketAnalyticsWorkspace(p:SessionPrincipal){assertAdminPermission(p,"analytics.market.read");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.marketAnalytics(p);return memory.adminMarketAnalyticsWorkspace(p);}
export async function adminMaintenanceWorkspace(p:SessionPrincipal){assertAdminPermission(p,"admin.audit.read");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.maintenanceWorkspace(p);return memory.adminMaintenanceWorkspace(p);}
export async function adminRunMaintenance(p:SessionPrincipal){assertAdminPermission(p,"admin.audit.read");if(!hasAdminPermission(p,"catalog.write")&&!hasAdminPermission(p,"vendor.manage"))throw new Error("Operational maintenance requires elevated platform permissions");if(postgresAdminRuntimeEnabled())return getProductionPostgresRuntime().adminGovernance.runMaintenance(p);return memory.adminRunMaintenance(p);}
