import { createHash, createHmac, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { hashPassword, verifyPassword, type SessionPrincipal } from "@buy-local-sparta/core";
import type { PoolClient } from "pg";
import { getProductionPostgresRuntime, productionDatabaseConfigured } from "./postgres-runtime";

export const DRIVER_SESSION_COOKIE = "bls_driver_session";
const DRIVER_SESSION_TTL_MS = 12 * 60 * 60 * 1000;
const LOCATION_RETENTION_MS = 30 * 24 * 60 * 60 * 1000;

export type DeliveryDriverPrincipal = Readonly<{ driverId: string; driverPublicId: string; userId: string; email: string; displayName: string; partnerId: string; partnerName: string; csrfToken: string; sessionId: string }>;
export type DeliveryStopView = Readonly<{ id: string; sequence: number; kind: string; status: string; vendorId?: string; vendorName?: string; address: Record<string, unknown>; completedAt?: number; sourceStatus?: string; receiptQr?: string }>;
export type DeliveryJobView = Readonly<{ id: string; orderId: string; type: "outbound" | "return"; status: string; driverId?: string; driverName?: string; partnerName?: string; liveTracking: boolean; pickupQr?: string; customerQr?: string; returnPickupQr?: string; stops: readonly DeliveryStopView[]; progress: { completed: number; total: number }; latestLocation?: { latitude: number; longitude: number; accuracy?: number; receivedAt: number } }>;

function runtime() { if (!productionDatabaseConfigured()) throw new Error("Delivery operations require the production database"); return getProductionPostgresRuntime(); }
function signingKey(context: string): Buffer { const source=process.env.BLS_DELIVERY_SIGNING_SECRET?.trim()||process.env.BLS_AUTH_SECRET?.trim(); if(!source||source.length<32) throw new Error("Delivery signing secret is not configured"); return createHmac("sha256",source).update(`kontamou:delivery:${context}:v1`).digest(); }
function sha256(value: string): string { return createHash("sha256").update(value).digest("hex"); }
function safeEqual(a: string,b: string): boolean { const aa=Buffer.from(a,"utf8"),bb=Buffer.from(b,"utf8"); return aa.length===bb.length&&timingSafeEqual(aa,bb); }
function proofToken(scope: "pickup"|"delivery"|"return-pickup"|"return-receipt",jobId:string,stopId?:string):string { const stop=stopId??"-"; const payload=`${scope}|${jobId}|${stop}`; const sig=createHmac("sha256",signingKey("proof")).update(payload).digest("base64url"); return `kmd1.${scope}.${jobId}.${stop}.${sig}`; }
function parseProof(token:string){ const parts=token.trim().split("."); if(parts.length!==5||parts[0]!=="kmd1") throw new Error("Μη έγκυρο QR παράδοσης."); const [,scope,jobId,stopPart,sig]=parts; if(!["pickup","delivery","return-pickup","return-receipt"].includes(scope)||!/^delivery_job_[a-f0-9]{32}$/.test(jobId)||(stopPart!=="-"&&!/^delivery_stop_[a-f0-9]{32}$/.test(stopPart))) throw new Error("Μη έγκυρο QR παράδοσης."); const expected=createHmac("sha256",signingKey("proof")).update(`${scope}|${jobId}|${stopPart}`).digest("base64url"); if(!safeEqual(sig,expected)) throw new Error("Μη έγκυρο QR παράδοσης."); return {scope,jobId,stopId:stopPart==="-"?undefined:stopPart}; }
function assertProofHash(token:string,storedHash:string|null|undefined){ if(!storedHash||!safeEqual(sha256(token),storedHash)) throw new Error("Το QR δεν είναι πλέον έγκυρο."); }
function sessionToken(raw:string){ const sig=createHmac("sha256",signingKey("session")).update(raw).digest("base64url"); return `${raw}.${sig}`; }
function verifySessionToken(token:string){ const dot=token.lastIndexOf("."); if(dot<=0)return false; const raw=token.slice(0,dot),supplied=token.slice(dot+1),expected=createHmac("sha256",signingKey("session")).update(raw).digest("base64url"); return safeEqual(supplied,expected); }
function csrfForSession(token:string){ return createHmac("sha256",signingKey("csrf")).update(token).digest("base64url"); }

export async function authenticateDeliveryDriver(input:{email:string;password:string;now:number}){
  const email=input.email.trim().toLowerCase(); if(!email||!input.password) throw new Error("Email και κωδικός είναι υποχρεωτικά.");
  const result=await runtime().nativePool.query<{user_uuid:string;user_id:string;email:string;password_hash:string|null;user_status:string;driver_uuid:string;driver_id:string;display_name:string;driver_status:string;partner_id:string;partner_name:string;partner_active:boolean}>(`
    SELECT u.id::text user_uuid,u.public_id user_id,u.email::text email,u.password_hash,u.status::text user_status,d.id::text driver_uuid,d.public_id driver_id,d.display_name,d.status driver_status,p.public_id partner_id,p.name partner_name,p.active partner_active
    FROM users u JOIN delivery_drivers d ON d.user_id=u.id JOIN delivery_partners p ON p.id=d.partner_id WHERE lower(u.email::text)=lower($1) LIMIT 1`,[email]);
  const row=result.rows[0]; if(!row?.password_hash||!verifyPassword(input.password,row.password_hash)||row.user_status!=="active"||row.driver_status!=="active"||!row.partner_active) throw new Error("Λανθασμένα στοιχεία ή ανενεργός λογαριασμός οδηγού.");
  const token=sessionToken(randomBytes(32).toString("base64url")),csrf=csrfForSession(token),expiresAt=input.now+DRIVER_SESSION_TTL_MS,sessionId=`driver_session_${randomUUID().replaceAll("-","")}`;
  await runtime().nativePool.query(`INSERT INTO delivery_driver_sessions(id,public_id,driver_id,token_hash,csrf_token_hash,created_at,last_seen_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$6,$7)`,[randomUUID(),sessionId,row.driver_uuid,sha256(token),sha256(csrf),new Date(input.now),new Date(expiresAt)]);
  return {token,expiresAt,principal:{driverId:row.driver_uuid,driverPublicId:row.driver_id,userId:row.user_id,email:row.email,displayName:row.display_name,partnerId:row.partner_id,partnerName:row.partner_name,csrfToken:csrf,sessionId} satisfies DeliveryDriverPrincipal};
}

export async function deliveryDriverSession(token:string|undefined,now=Date.now()):Promise<DeliveryDriverPrincipal|undefined>{
  if(!token||!verifySessionToken(token)) return undefined; const csrf=csrfForSession(token);
  const result=await runtime().nativePool.query<{session_id:string;csrf_token_hash:string;user_id:string;email:string;user_status:string;driver_uuid:string;driver_id:string;display_name:string;driver_status:string;partner_id:string;partner_name:string;partner_active:boolean}>(`
    SELECT s.public_id session_id,s.csrf_token_hash,u.public_id user_id,u.email::text email,u.status::text user_status,d.id::text driver_uuid,d.public_id driver_id,d.display_name,d.status driver_status,p.public_id partner_id,p.name partner_name,p.active partner_active
    FROM delivery_driver_sessions s JOIN delivery_drivers d ON d.id=s.driver_id JOIN users u ON u.id=d.user_id JOIN delivery_partners p ON p.id=d.partner_id
    WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>$2 LIMIT 1`,[sha256(token),new Date(now)]);
  const row=result.rows[0]; if(!row||row.user_status!=="active"||row.driver_status!=="active"||!row.partner_active||!safeEqual(row.csrf_token_hash,sha256(csrf))) return undefined;
  await runtime().nativePool.query("UPDATE delivery_driver_sessions SET last_seen_at=$2 WHERE public_id=$1",[row.session_id,new Date(now)]);
  return {driverId:row.driver_uuid,driverPublicId:row.driver_id,userId:row.user_id,email:row.email,displayName:row.display_name,partnerId:row.partner_id,partnerName:row.partner_name,csrfToken:csrf,sessionId:row.session_id};
}
export function assertDeliveryDriverCsrf(principal:DeliveryDriverPrincipal,supplied:string|undefined){ if(!supplied||!safeEqual(principal.csrfToken,supplied)) throw new Error("CSRF validation failed"); }
export async function logoutDeliveryDriver(token:string|undefined,now=Date.now()){ if(!token||!verifySessionToken(token))return; const db=runtime(); const result=await db.nativePool.query<{driver_id:string}>("UPDATE delivery_driver_sessions SET revoked_at=COALESCE(revoked_at,$2) WHERE token_hash=$1 RETURNING driver_id::text driver_id",[sha256(token),new Date(now)]); if(result.rows[0]?.driver_id) await db.nativePool.query("UPDATE delivery_jobs SET live_tracking_enabled=false,updated_at=$2 WHERE driver_id=$1 AND status IN ('assigned','in_progress')",[result.rows[0].driver_id,new Date(now)]); }

export async function adminCreateDeliveryDriver(_principal:SessionPrincipal,input:{partnerName:string;displayName:string;email:string;phone?:string;password:string;now?:number}){
  const partnerName=input.partnerName.trim(),displayName=input.displayName.trim(),email=input.email.trim().toLowerCase(); if(!partnerName||!displayName||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new Error("Συμπλήρωσε συνεργάτη, όνομα οδηγού και έγκυρο email."); const passwordHash=hashPassword(input.password),now=input.now??Date.now(),client=await runtime().nativePool.connect();
  try{ await client.query("BEGIN"); if((await client.query("SELECT 1 FROM users WHERE lower(email::text)=lower($1) LIMIT 1",[email])).rowCount) throw new Error("Το email χρησιμοποιείται ήδη από άλλο λογαριασμό.");
    const partner=await client.query<{id:string;public_id:string}>(`INSERT INTO delivery_partners(name,active,created_at,updated_at) VALUES($1,true,$2,$2) ON CONFLICT (lower(name)) DO UPDATE SET active=true,updated_at=EXCLUDED.updated_at RETURNING id::text id,public_id`,[partnerName,new Date(now)]);
    const user=await client.query<{id:string;public_id:string}>(`INSERT INTO users(email,password_hash,status,email_verified_at,preferred_locale,created_at,updated_at) VALUES($1,$2,'active',$3,'el',$3,$3) RETURNING id::text id,public_id`,[email,passwordHash,new Date(now)]);
    const driver=await client.query<{public_id:string}>(`INSERT INTO delivery_drivers(partner_id,user_id,display_name,phone,status,created_at,updated_at) VALUES($1,$2,$3,$4,'active',$5,$5) RETURNING public_id`,[partner.rows[0].id,user.rows[0].id,displayName,input.phone?.trim()||null,new Date(now)]);
    await client.query("COMMIT"); return {driverId:driver.rows[0].public_id,userId:user.rows[0].public_id,partnerId:partner.rows[0].public_id};
  }catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}
}
export async function adminSetDeliveryDriverStatus(_principal:SessionPrincipal,input:{driverId:string;status:"active"|"inactive"|"suspended";now?:number}){ const now=input.now??Date.now(),db=runtime(); const result=await db.nativePool.query<{id:string}>("UPDATE delivery_drivers SET status=$2,updated_at=$3 WHERE public_id=$1 RETURNING id::text id",[input.driverId,input.status,new Date(now)]); if(!result.rowCount) throw new Error("Ο οδηγός δεν βρέθηκε."); if(input.status!=="active"){await db.nativePool.query("UPDATE delivery_driver_sessions SET revoked_at=COALESCE(revoked_at,$2) WHERE driver_id=$1",[result.rows[0].id,new Date(now)]);await db.nativePool.query("UPDATE delivery_jobs SET live_tracking_enabled=false,updated_at=$2 WHERE driver_id=$1 AND status IN ('assigned','in_progress')",[result.rows[0].id,new Date(now)]);} return {ok:true}; }
export async function adminResetDeliveryDriverPassword(_principal:SessionPrincipal,input:{driverId:string;password:string;now?:number}){ const now=input.now??Date.now(),db=runtime(),passwordHash=hashPassword(input.password); const result=await db.nativePool.query<{driver_uuid:string}>(`UPDATE users u SET password_hash=$2,updated_at=$3 FROM delivery_drivers d WHERE d.user_id=u.id AND d.public_id=$1 RETURNING d.id::text driver_uuid`,[input.driverId,passwordHash,new Date(now)]); if(!result.rowCount) throw new Error("Ο οδηγός δεν βρέθηκε."); await db.nativePool.query("UPDATE delivery_driver_sessions SET revoked_at=COALESCE(revoked_at,$2) WHERE driver_id=$1",[result.rows[0].driver_uuid,new Date(now)]); return {ok:true}; }

async function appendDeliveryEvent(client:PoolClient,input:{jobUuid:string;stopUuid?:string;eventType:string;actorType:string;actorPublicId?:string;customerVisible?:boolean;message:string;metadata?:Record<string,unknown>;now:number}){ await client.query(`INSERT INTO delivery_events(id,public_id,job_id,stop_id,event_type,actor_type,actor_public_id,customer_visible,message,metadata,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11)`,[randomUUID(),`delivery_event_${randomUUID().replaceAll("-","")}`,input.jobUuid,input.stopUuid??null,input.eventType,input.actorType,input.actorPublicId??null,input.customerVisible??false,input.message,JSON.stringify(input.metadata??{}),new Date(input.now)]); }

async function ensureOutboundJobs(client:PoolClient,now:number){
  const result=await client.query<{order_uuid:string;order_id:string;market_uuid:string;shipping_address:Record<string,unknown>;fulfilment_uuid:string;fulfilment_status:string;vendor_uuid:string;vendor_name:string;location_uuid:string;location_name:string;vendor_address:Record<string,unknown>}>(`
    SELECT o.id::text order_uuid,o.public_id order_id,o.market_id::text market_uuid,o.shipping_address_snapshot shipping_address,fo.id::text fulfilment_uuid,fo.status::text fulfilment_status,vb.id::text vendor_uuid,vb.trading_name vendor_name,vl.id::text location_uuid,vl.name location_name,
    jsonb_build_object('name',vl.name,'line1',vl.address_line1,'line2',vl.address_line2,'locality',vl.locality,'postcode',vl.postcode,'countryCode',vl.country_code,'phone',vl.phone) vendor_address
    FROM fulfilment_orders fo JOIN customer_orders o ON o.id=fo.order_id JOIN vendor_businesses vb ON vb.id=fo.vendor_id JOIN vendor_locations vl ON vl.id=fo.location_id
    WHERE fo.mode='local_delivery' AND fo.status NOT IN ('delivered','rejected','cancelled','failed') AND o.status NOT IN ('cancelled','refunded') ORDER BY o.created_at,fo.created_at`);
  const groups=new Map<string,typeof result.rows>(); for(const row of result.rows){const group=groups.get(row.order_uuid)??[];group.push(row);groups.set(row.order_uuid,group);} for(const rows of groups.values()){const first=rows[0]; const job=(await client.query<{id:string;public_id:string;status:string}>(`INSERT INTO delivery_jobs(market_id,order_id,job_type,source_key,status,created_at,updated_at) VALUES($1,$2,'outbound',$3,'queued',$4,$4) ON CONFLICT (source_key) DO UPDATE SET updated_at=EXCLUDED.updated_at RETURNING id::text id,public_id,status`,[first.market_uuid,first.order_uuid,`outbound:${first.order_uuid}`,new Date(now)])).rows[0]; let sequence=10,ready=false;
    for(const row of rows){const stopStatus=row.fulfilment_status==="handed_over"?"completed":row.fulfilment_status==="ready_for_handover"?"ready":"pending";ready||=stopStatus==="ready"; await client.query(`INSERT INTO delivery_stops(job_id,sequence_no,stop_kind,vendor_id,location_id,fulfilment_order_id,address_snapshot,contact_snapshot,status,completed_at,created_at,updated_at) VALUES($1,$2,'vendor_pickup',$3,$4,$5,$6::jsonb,$7::jsonb,$8,CASE WHEN $8='completed' THEN $9 ELSE NULL END,$9,$9) ON CONFLICT (fulfilment_order_id) WHERE fulfilment_order_id IS NOT NULL DO UPDATE SET status=CASE WHEN delivery_stops.status='completed' THEN 'completed' ELSE EXCLUDED.status END,address_snapshot=EXCLUDED.address_snapshot,updated_at=EXCLUDED.updated_at`,[job.id,sequence,row.vendor_uuid,row.location_uuid,row.fulfilment_uuid,JSON.stringify(row.vendor_address),JSON.stringify({vendorName:row.vendor_name,locationName:row.location_name}),stopStatus,new Date(now)]);sequence+=10;}
    if(!(await client.query("SELECT 1 FROM delivery_stops WHERE job_id=$1 AND stop_kind='customer_dropoff' LIMIT 1",[job.id])).rowCount) await client.query(`INSERT INTO delivery_stops(job_id,sequence_no,stop_kind,address_snapshot,status,created_at,updated_at) VALUES($1,10000,'customer_dropoff',$2::jsonb,'pending',$3,$3)`,[job.id,JSON.stringify(first.shipping_address??{}),new Date(now)]);
    const pickup=proofToken("pickup",job.public_id),delivery=proofToken("delivery",job.public_id),targetStatus=job.status==="queued"&&ready?"ready":job.status; await client.query("UPDATE delivery_jobs SET pickup_proof_hash=$2,customer_proof_hash=$3,status=$4,updated_at=$5 WHERE id=$1",[job.id,sha256(pickup),sha256(delivery),targetStatus,new Date(now)]);
  }
}

async function ensureReturnJobs(client:PoolClient,now:number){
  const result=await client.query<{return_uuid:string;order_uuid:string;market_uuid:string;shipping_address:Record<string,unknown>;vendor_uuid:string;vendor_name:string;location_uuid:string;vendor_address:Record<string,unknown>}>(`
    SELECT r.id::text return_uuid,o.id::text order_uuid,o.market_id::text market_uuid,o.shipping_address_snapshot shipping_address,vb.id::text vendor_uuid,vb.trading_name vendor_name,vl.id::text location_uuid,jsonb_build_object('name',vl.name,'line1',vl.address_line1,'line2',vl.address_line2,'locality',vl.locality,'postcode',vl.postcode,'countryCode',vl.country_code,'phone',vl.phone) vendor_address
    FROM returns r JOIN customer_orders o ON o.id=r.order_id JOIN vendor_businesses vb ON vb.id=COALESCE(r.destination_vendor_id,r.vendor_id) JOIN LATERAL (SELECT x.* FROM vendor_locations x WHERE x.vendor_id=vb.id AND x.active=true ORDER BY x.is_primary DESC,x.created_at LIMIT 1) vl ON true
    WHERE r.status IN ('approved','in_transit') AND NOT EXISTS (SELECT 1 FROM delivery_job_returns djr WHERE djr.return_id=r.id) ORDER BY r.created_at`);
  const groups=new Map<string,typeof result.rows>();for(const row of result.rows){const group=groups.get(row.order_uuid)??[];group.push(row);groups.set(row.order_uuid,group);}for(const rows of groups.values()){const first=rows[0],job=(await client.query<{id:string;public_id:string}>(`INSERT INTO delivery_jobs(market_id,order_id,job_type,source_key,status,created_at,updated_at) VALUES($1,$2,'return',$3,'ready',$4,$4) RETURNING id::text id,public_id`,[first.market_uuid,first.order_uuid,`return:${first.return_uuid}`,new Date(now)])).rows[0]; await client.query(`INSERT INTO delivery_stops(job_id,sequence_no,stop_kind,address_snapshot,status,created_at,updated_at) VALUES($1,10,'customer_return_pickup',$2::jsonb,'ready',$3,$3)`,[job.id,JSON.stringify(first.shipping_address??{}),new Date(now)]);let sequence=100;
    for(const row of rows){await client.query("INSERT INTO delivery_job_returns(job_id,return_id,created_at) VALUES($1,$2,$3)",[job.id,row.return_uuid,new Date(now)]);const stop=(await client.query<{public_id:string}>(`INSERT INTO delivery_stops(job_id,sequence_no,stop_kind,vendor_id,location_id,return_id,address_snapshot,contact_snapshot,status,created_at,updated_at) VALUES($1,$2,'vendor_return_dropoff',$3,$4,$5,$6::jsonb,$7::jsonb,'pending',$8,$8) RETURNING public_id`,[job.id,sequence,row.vendor_uuid,row.location_uuid,row.return_uuid,JSON.stringify(row.vendor_address),JSON.stringify({vendorName:row.vendor_name}),new Date(now)])).rows[0];await client.query("UPDATE delivery_stops SET proof_hash=$2 WHERE public_id=$1",[stop.public_id,sha256(proofToken("return-receipt",job.public_id,stop.public_id))]);sequence+=10;}
    await client.query("UPDATE delivery_jobs SET return_customer_proof_hash=$2,updated_at=$3 WHERE id=$1",[job.id,sha256(proofToken("return-pickup",job.public_id)),new Date(now)]);
  }
}
export async function synchronizeDeliveryJobs(now=Date.now()){const client=await runtime().nativePool.connect();try{await client.query("BEGIN");await ensureOutboundJobs(client,now);await ensureReturnJobs(client,now);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}}

async function loadJobViews(whereSql:string,params:readonly unknown[],proofs:"driver"|"customer"|"none"):Promise<readonly DeliveryJobView[]>{
  const result=await runtime().nativePool.query<{job_id:string;order_id:string;job_type:"outbound"|"return";status:string;driver_id:string|null;driver_name:string|null;partner_name:string|null;live_tracking:boolean;pickup_hash:string|null;customer_hash:string|null;return_pickup_hash:string|null;stops:Array<{id:string;sequence:number;kind:string;status:string;vendorId?:string;vendorName?:string;address:Record<string,unknown>;completedAt?:string;sourceStatus?:string}>;latitude:number|null;longitude:number|null;accuracy_m:number|null;ping_received_at:Date|null}>(`
    SELECT j.public_id job_id,o.public_id order_id,j.job_type,j.status,d.public_id driver_id,d.display_name driver_name,p.name partner_name,j.live_tracking_enabled live_tracking,j.pickup_proof_hash pickup_hash,j.customer_proof_hash customer_hash,j.return_customer_proof_hash return_pickup_hash,
    COALESCE((SELECT jsonb_agg(jsonb_build_object('id',s.public_id,'sequence',s.sequence_no,'kind',s.stop_kind,'status',s.status,'vendorId',vb.public_id,'vendorName',vb.trading_name,'address',s.address_snapshot,'completedAt',s.completed_at,'sourceStatus',fo.status::text) ORDER BY s.sequence_no) FROM delivery_stops s LEFT JOIN vendor_businesses vb ON vb.id=s.vendor_id LEFT JOIN fulfilment_orders fo ON fo.id=s.fulfilment_order_id WHERE s.job_id=j.id),'[]'::jsonb) stops,
    lp.latitude,lp.longitude,lp.accuracy_m,lp.received_at ping_received_at
    FROM delivery_jobs j JOIN customer_orders o ON o.id=j.order_id LEFT JOIN delivery_drivers d ON d.id=j.driver_id LEFT JOIN delivery_partners p ON p.id=j.partner_id LEFT JOIN LATERAL (SELECT x.latitude,x.longitude,x.accuracy_m,x.received_at FROM delivery_location_pings x WHERE x.job_id=j.id AND x.expires_at>now() ORDER BY x.received_at DESC LIMIT 1) lp ON true WHERE ${whereSql}
    ORDER BY CASE j.status WHEN 'in_progress' THEN 0 WHEN 'assigned' THEN 1 WHEN 'ready' THEN 2 ELSE 3 END,j.created_at DESC LIMIT 100`,[...params]);
  return result.rows.map(row=>{const stops=(row.stops??[]).map(stop=>({id:stop.id,sequence:Number(stop.sequence),kind:stop.kind,status:stop.status,vendorId:stop.vendorId||undefined,vendorName:stop.vendorName||undefined,address:stop.address??{},completedAt:stop.completedAt?new Date(stop.completedAt).getTime():undefined,sourceStatus:stop.sourceStatus||undefined}));const completed=stops.filter(stop=>["completed","skipped"].includes(stop.status)).length;return {id:row.job_id,orderId:row.order_id,type:row.job_type,status:row.status,driverId:row.driver_id??undefined,driverName:row.driver_name??undefined,partnerName:row.partner_name??undefined,liveTracking:row.live_tracking,pickupQr:proofs==="driver"&&row.job_type==="outbound"&&row.pickup_hash?proofToken("pickup",row.job_id):undefined,customerQr:proofs==="customer"&&row.job_type==="outbound"&&row.customer_hash?proofToken("delivery",row.job_id):undefined,returnPickupQr:proofs==="customer"&&row.job_type==="return"&&row.return_pickup_hash?proofToken("return-pickup",row.job_id):undefined,stops,progress:{completed,total:stops.length},latestLocation:row.latitude!=null&&row.longitude!=null&&row.ping_received_at?{latitude:Number(row.latitude),longitude:Number(row.longitude),accuracy:row.accuracy_m==null?undefined:Number(row.accuracy_m),receivedAt:row.ping_received_at.getTime()}:undefined} satisfies DeliveryJobView;});
}

export async function deliveryDriverWorkspace(principal:DeliveryDriverPrincipal){await synchronizeDeliveryJobs();const [assigned,available]=await Promise.all([loadJobViews("j.driver_id=$1 AND j.status IN ('assigned','in_progress','ready','queued')",[principal.driverId],"driver"),loadJobViews("j.driver_id IS NULL AND j.status='ready'",[],"none")]);return {csrfToken:principal.csrfToken,assigned,available:available.map(job=>({...job,stops:job.stops.map(stop=>stop.kind.startsWith("customer")?{...stop,address:{}}:stop)}))};}
export async function deliveryAdminWorkspace(_principal:SessionPrincipal){await synchronizeDeliveryJobs();const db=runtime(),[drivers,jobs]=await Promise.all([db.nativePool.query<{id:string;display_name:string;email:string;phone:string|null;status:string;partner_name:string}>(`SELECT d.public_id id,d.display_name,u.email::text email,d.phone,d.status,p.name partner_name FROM delivery_drivers d JOIN users u ON u.id=d.user_id JOIN delivery_partners p ON p.id=d.partner_id ORDER BY d.created_at DESC`),loadJobViews("j.status<>'cancelled'",[],"none")]);return {drivers:drivers.rows.map(row=>({id:row.id,name:row.display_name,email:row.email,phone:row.phone??undefined,status:row.status,partnerName:row.partner_name})),jobs};}
export async function deliveryVendorWorkspace(principal:SessionPrincipal){if(!principal.vendorId) throw new Error("VENDOR_AUTH_REQUIRED");await synchronizeDeliveryJobs();const vendor=await runtime().nativePool.query<{id:string}>("SELECT id::text id FROM vendor_businesses WHERE public_id=$1 LIMIT 1",[principal.vendorId]);if(!vendor.rowCount)throw new Error("Vendor not found");const jobs=await loadJobViews("EXISTS (SELECT 1 FROM delivery_stops s WHERE s.job_id=j.id AND s.vendor_id=$1 AND s.status NOT IN ('completed','skipped'))",[vendor.rows[0].id],"none");return {jobs:jobs.map(job=>({...job,stops:job.stops.map(stop=>stop.vendorId===principal.vendorId&&stop.kind==="vendor_return_dropoff"&&stop.status!=="completed"?{...stop,receiptQr:proofToken("return-receipt",job.id,stop.id)}:stop)}))};}
export async function deliveryCustomerWorkspace(principal:SessionPrincipal){await synchronizeDeliveryJobs();const user=await runtime().nativePool.query<{id:string}>("SELECT id::text id FROM users WHERE public_id=$1 LIMIT 1",[principal.userId]);if(!user.rowCount)return {jobs:[] as readonly DeliveryJobView[]};return {jobs:await loadJobViews("o.user_id=$1 AND j.status<>'cancelled'",[user.rows[0].id],"customer")};}

export async function adminAssignDeliveryJob(_principal:SessionPrincipal,input:{jobId:string;driverId:string;now?:number}){const now=input.now??Date.now(),client=await runtime().nativePool.connect();try{await client.query("BEGIN");const driver=await client.query<{id:string;partner_id:string;name:string}>(`SELECT d.id::text id,d.partner_id::text partner_id,d.display_name name FROM delivery_drivers d JOIN delivery_partners p ON p.id=d.partner_id WHERE d.public_id=$1 AND d.status='active' AND p.active=true FOR UPDATE`,[input.driverId]);if(!driver.rowCount)throw new Error("Ο οδηγός δεν είναι ενεργός.");const job=await client.query<{id:string}>(`UPDATE delivery_jobs SET driver_id=$2,partner_id=$3,status='assigned',assigned_at=$4,updated_at=$4 WHERE public_id=$1 AND status IN ('queued','ready','assigned') AND completed_at IS NULL RETURNING id::text id`,[input.jobId,driver.rows[0].id,driver.rows[0].partner_id,new Date(now)]);if(!job.rowCount)throw new Error("Η εργασία δεν μπορεί να ανατεθεί.");await appendDeliveryEvent(client,{jobUuid:job.rows[0].id,eventType:"job.assigned",actorType:"admin",customerVisible:false,message:`Ανάθεση στον οδηγό ${driver.rows[0].name}.`,now});await client.query("COMMIT");return {ok:true};}catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}}
export async function driverClaimDeliveryJob(principal:DeliveryDriverPrincipal,jobId:string,now=Date.now()){const client=await runtime().nativePool.connect();try{await client.query("BEGIN");const result=await client.query<{id:string}>(`UPDATE delivery_jobs SET driver_id=$2,partner_id=(SELECT partner_id FROM delivery_drivers WHERE id=$2),status='assigned',assigned_at=$3,updated_at=$3 WHERE public_id=$1 AND driver_id IS NULL AND status='ready' RETURNING id::text id`,[jobId,principal.driverId,new Date(now)]);if(!result.rowCount)throw new Error("Η εργασία έχει ήδη ανατεθεί ή δεν είναι έτοιμη.");await appendDeliveryEvent(client,{jobUuid:result.rows[0].id,eventType:"job.claimed",actorType:"driver",actorPublicId:principal.driverPublicId,customerVisible:false,message:`Η εργασία αναλήφθηκε από ${principal.displayName}.`,now});await client.query("COMMIT");return {ok:true};}catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}}
export async function driverSetLiveTracking(principal:DeliveryDriverPrincipal,input:{jobId:string;enabled:boolean;now?:number}){const now=input.now??Date.now();const result=await runtime().nativePool.query(`UPDATE delivery_jobs SET live_tracking_enabled=$3,status=CASE WHEN $3 AND status IN ('assigned','ready') THEN 'in_progress' ELSE status END,started_at=CASE WHEN $3 THEN COALESCE(started_at,$4) ELSE started_at END,updated_at=$4 WHERE public_id=$1 AND driver_id=$2 AND status IN ('assigned','in_progress','ready') RETURNING public_id`,[input.jobId,principal.driverId,input.enabled,new Date(now)]);if(!result.rowCount)throw new Error("Η εργασία δεν είναι ενεργή ή δεν σου έχει ανατεθεί.");return {ok:true};}
export async function recordDeliveryLocation(principal:DeliveryDriverPrincipal,input:{jobId:string;latitude:number;longitude:number;accuracy?:number;heading?:number;speed?:number;deviceRecordedAt?:number;now?:number}){const now=input.now??Date.now();if(!Number.isFinite(input.latitude)||input.latitude< -90||input.latitude>90||!Number.isFinite(input.longitude)||input.longitude< -180||input.longitude>180)throw new Error("Invalid coordinates");const db=runtime(),job=await db.nativePool.query<{id:string}>("SELECT id::text id FROM delivery_jobs WHERE public_id=$1 AND driver_id=$2 AND live_tracking_enabled=true AND status='in_progress' LIMIT 1",[input.jobId,principal.driverId]);if(!job.rowCount)throw new Error("Η live παρακολούθηση δεν είναι ενεργή για αυτή την εργασία.");if((await db.nativePool.query("SELECT 1 FROM delivery_location_pings WHERE job_id=$1 AND received_at>$2 LIMIT 1",[job.rows[0].id,new Date(now-7000)])).rowCount)return {accepted:false,reason:"throttled" as const};await db.nativePool.query(`INSERT INTO delivery_location_pings(job_id,driver_id,latitude,longitude,accuracy_m,heading_deg,speed_mps,device_recorded_at,received_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[job.rows[0].id,principal.driverId,input.latitude,input.longitude,input.accuracy!=null&&Number.isFinite(input.accuracy)?input.accuracy:null,input.heading!=null&&Number.isFinite(input.heading)&&input.heading>=0&&input.heading<=360?input.heading:null,input.speed!=null&&Number.isFinite(input.speed)&&input.speed>=0?input.speed:null,input.deviceRecordedAt?new Date(input.deviceRecordedAt):null,new Date(now),new Date(now+LOCATION_RETENTION_MS)]);return {accepted:true};}

async function recomputeOrderStatus(client:PoolClient,orderUuid:string,now:number){const summary=await client.query<{open_count:string;done_count:string}>(`SELECT COUNT(*) FILTER (WHERE CASE WHEN mode='pickup' THEN status NOT IN ('handed_over','delivered','rejected','cancelled') ELSE status NOT IN ('delivered','rejected','cancelled') END)::text open_count,COUNT(*) FILTER (WHERE CASE WHEN mode='pickup' THEN status IN ('handed_over','delivered') ELSE status='delivered' END)::text done_count FROM fulfilment_orders WHERE order_id=$1`,[orderUuid]);const open=Number(summary.rows[0]?.open_count??0),done=Number(summary.rows[0]?.done_count??0);if(open===0&&done>0)await client.query("UPDATE customer_orders SET status='fulfilled',updated_at=$2 WHERE id=$1 AND status NOT IN ('cancelled','refunded')",[orderUuid,new Date(now)]);else if(done>0)await client.query("UPDATE customer_orders SET status='partially_fulfilled',updated_at=$2 WHERE id=$1 AND status NOT IN ('cancelled','refunded')",[orderUuid,new Date(now)]);}

export async function vendorConfirmDriverPickup(principal:SessionPrincipal,token:string,now=Date.now()){
  if(!principal.vendorId)throw new Error("VENDOR_AUTH_REQUIRED");const parsed=parseProof(token);if(parsed.scope!=="pickup"||parsed.stopId)throw new Error("Αυτό δεν είναι QR παραλαβής οδηγού.");const client=await runtime().nativePool.connect();try{await client.query("BEGIN");const result=await client.query<{job_uuid:string;job_id:string;pickup_hash:string|null;driver_uuid:string|null;stop_uuid:string;stop_status:string;fulfilment_uuid:string;fulfilment_status:string;order_uuid:string;order_id:string;vendor_uuid:string;vendor_name:string}>(`
    SELECT j.id::text job_uuid,j.public_id job_id,j.pickup_proof_hash pickup_hash,d.id::text driver_uuid,s.id::text stop_uuid,s.status stop_status,fo.id::text fulfilment_uuid,fo.status::text fulfilment_status,o.id::text order_uuid,o.public_id order_id,vb.id::text vendor_uuid,vb.trading_name vendor_name
    FROM delivery_jobs j JOIN delivery_stops s ON s.job_id=j.id AND s.stop_kind='vendor_pickup' JOIN fulfilment_orders fo ON fo.id=s.fulfilment_order_id JOIN customer_orders o ON o.id=j.order_id JOIN vendor_businesses vb ON vb.id=s.vendor_id LEFT JOIN delivery_drivers d ON d.id=j.driver_id WHERE j.public_id=$1 AND vb.public_id=$2 LIMIT 1 FOR UPDATE OF j,s,fo`,[parsed.jobId,principal.vendorId]);const row=result.rows[0];if(!row)throw new Error("Το QR δεν αντιστοιχεί σε παραλαβή αυτού του καταστήματος.");assertProofHash(token,row.pickup_hash);if(!row.driver_uuid)throw new Error("Η εργασία δεν έχει ακόμη ανατεθεί σε οδηγό.");if(row.stop_status==="completed"){await client.query("COMMIT");return {ok:true,alreadyCompleted:true};}if(row.fulfilment_status!=="ready_for_handover")throw new Error("Η παραγγελία δεν είναι ακόμη έτοιμη για παράδοση στον οδηγό.");await client.query("UPDATE delivery_stops SET status='completed',completed_at=$2,completed_by_driver_id=$3,updated_at=$2 WHERE id=$1",[row.stop_uuid,new Date(now),row.driver_uuid]);await client.query("UPDATE fulfilment_orders SET status='handed_over',updated_at=$2 WHERE id=$1",[row.fulfilment_uuid,new Date(now)]);await client.query("UPDATE delivery_jobs SET status='in_progress',started_at=COALESCE(started_at,$2),updated_at=$2 WHERE id=$1",[row.job_uuid,new Date(now)]);const progress=await client.query<{done:string;total:string}>("SELECT COUNT(*) FILTER (WHERE status='completed')::text done,COUNT(*)::text total FROM delivery_stops WHERE job_id=$1 AND stop_kind='vendor_pickup'",[row.job_uuid]);const done=Number(progress.rows[0]?.done??0),total=Number(progress.rows[0]?.total??0),message=`${row.vendor_name}: παραλαβή από τον οδηγό ολοκληρώθηκε · ${done}/${total} σημεία παραλαβής.`;await appendDeliveryEvent(client,{jobUuid:row.job_uuid,stopUuid:row.stop_uuid,eventType:"pickup.vendor_confirmed",actorType:"vendor",actorPublicId:principal.userId,customerVisible:true,message,metadata:{orderId:row.order_id,progress:{done,total}},now});await client.query(`INSERT INTO order_timeline_events(id,public_id,order_id,fulfilment_order_id,vendor_id,event_type,actor_type,actor_public_id,customer_visible,message,metadata,created_at) VALUES($1,$2,$3,$4,$5,'delivery.vendor_pickup','vendor',$6,true,$7,$8::jsonb,$9)`,[randomUUID(),`ote_${randomUUID().replaceAll("-","")}`,row.order_uuid,row.fulfilment_uuid,row.vendor_uuid,principal.userId,message,JSON.stringify({deliveryJobId:row.job_id,progress:{done,total}}),new Date(now)]);await client.query("COMMIT");return {ok:true,progress:{done,total}};}catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}
}

export async function driverScanDeliveryProof(principal:DeliveryDriverPrincipal,token:string,now=Date.now()){
  const parsed=parseProof(token);if(!["delivery","return-pickup","return-receipt"].includes(parsed.scope))throw new Error("Αυτό το QR δεν επιβεβαιώνεται από οδηγό.");const client=await runtime().nativePool.connect();try{await client.query("BEGIN");const job=await client.query<{job_uuid:string;job_id:string;order_uuid:string;order_id:string;customer_hash:string|null;return_pickup_hash:string|null;job_type:string;status:string}>(`SELECT j.id::text job_uuid,j.public_id job_id,o.id::text order_uuid,o.public_id order_id,j.customer_proof_hash customer_hash,j.return_customer_proof_hash return_pickup_hash,j.job_type,j.status FROM delivery_jobs j JOIN customer_orders o ON o.id=j.order_id WHERE j.public_id=$1 AND j.driver_id=$2 LIMIT 1 FOR UPDATE OF j`,[parsed.jobId,principal.driverId]);const row=job.rows[0];if(!row||!["assigned","in_progress","ready"].includes(row.status))throw new Error("Η εργασία δεν είναι ενεργή ή δεν σου έχει ανατεθεί.");
  if(parsed.scope==="delivery"){if(row.job_type!=="outbound"||parsed.stopId)throw new Error("Μη έγκυρο QR παράδοσης πελάτη.");assertProofHash(token,row.customer_hash);if((await client.query("SELECT 1 FROM delivery_stops WHERE job_id=$1 AND stop_kind='vendor_pickup' AND status<>'completed' LIMIT 1",[row.job_uuid])).rowCount)throw new Error("Δεν έχουν ολοκληρωθεί όλες οι παραλαβές από τα καταστήματα.");const stop=await client.query<{id:string;status:string}>("SELECT id::text id,status FROM delivery_stops WHERE job_id=$1 AND stop_kind='customer_dropoff' LIMIT 1 FOR UPDATE",[row.job_uuid]);if(!stop.rowCount)throw new Error("Δεν βρέθηκε σημείο παράδοσης.");if(stop.rows[0].status!=="completed"){await client.query("UPDATE delivery_stops SET status='completed',completed_at=$2,completed_by_driver_id=$3,updated_at=$2 WHERE id=$1",[stop.rows[0].id,new Date(now),principal.driverId]);await client.query(`UPDATE fulfilment_orders SET status='delivered',delivered_at=COALESCE(delivered_at,$2),updated_at=$2 WHERE id IN (SELECT fulfilment_order_id FROM delivery_stops WHERE job_id=$1 AND stop_kind='vendor_pickup' AND fulfilment_order_id IS NOT NULL)`,[row.job_uuid,new Date(now)]);await client.query(`UPDATE order_lines SET status='fulfilled',fulfilled_quantity=quantity,fulfilled_at=COALESCE(fulfilled_at,$2) WHERE id IN (SELECT fol.order_line_id FROM fulfilment_order_lines fol WHERE fol.fulfilment_order_id IN (SELECT fulfilment_order_id FROM delivery_stops WHERE job_id=$1 AND stop_kind='vendor_pickup' AND fulfilment_order_id IS NOT NULL))`,[row.job_uuid,new Date(now)]);await recomputeOrderStatus(client,row.order_uuid,now);await client.query("UPDATE delivery_jobs SET status='completed',completed_at=$2,live_tracking_enabled=false,updated_at=$2 WHERE id=$1",[row.job_uuid,new Date(now)]);const message=`Η παραγγελία ${row.order_id} παραδόθηκε επιτυχώς με επιβεβαίωση QR του πελάτη.`;await appendDeliveryEvent(client,{jobUuid:row.job_uuid,stopUuid:stop.rows[0].id,eventType:"delivery.customer_confirmed",actorType:"driver",actorPublicId:principal.driverPublicId,customerVisible:true,message,now});await client.query(`INSERT INTO order_timeline_events(id,public_id,order_id,event_type,actor_type,actor_public_id,customer_visible,message,metadata,created_at) VALUES($1,$2,$3,'delivery.completed','driver',$4,true,$5,$6::jsonb,$7)`,[randomUUID(),`ote_${randomUUID().replaceAll("-","")}`,row.order_uuid,principal.driverPublicId,message,JSON.stringify({deliveryJobId:row.job_id}),new Date(now)]);}await client.query("COMMIT");return {ok:true,completed:true};}
  if(parsed.scope==="return-pickup"){if(row.job_type!=="return"||parsed.stopId)throw new Error("Μη έγκυρο QR παραλαβής επιστροφής.");assertProofHash(token,row.return_pickup_hash);const stop=await client.query<{id:string;status:string}>("SELECT id::text id,status FROM delivery_stops WHERE job_id=$1 AND stop_kind='customer_return_pickup' LIMIT 1 FOR UPDATE",[row.job_uuid]);if(!stop.rowCount)throw new Error("Δεν βρέθηκε σημείο παραλαβής επιστροφής.");if(stop.rows[0].status!=="completed"){await client.query("UPDATE delivery_stops SET status='completed',completed_at=$2,completed_by_driver_id=$3,updated_at=$2 WHERE id=$1",[stop.rows[0].id,new Date(now),principal.driverId]);const returns=await client.query<{id:string}>("SELECT r.id::text id FROM returns r JOIN delivery_job_returns djr ON djr.return_id=r.id WHERE djr.job_id=$1",[row.job_uuid]);for(const item of returns.rows){await client.query("UPDATE returns SET status='in_transit',updated_at=$2 WHERE id=$1 AND status='approved'",[item.id,new Date(now)]);await client.query(`INSERT INTO return_custody_events(id,public_id,return_id,from_party,to_party,actor_public_id,reference,note,occurred_at) VALUES($1,$2,$3,'customer','delivery_driver',$4,$5,$6,$7)`,[randomUUID(),`return_custody_${randomUUID().replaceAll("-","")}`,item.id,principal.driverPublicId,row.job_id,"Παραλαβή επιστροφής από τον πελάτη με QR.",new Date(now)]);}await client.query("UPDATE delivery_jobs SET status='in_progress',started_at=COALESCE(started_at,$2),updated_at=$2 WHERE id=$1",[row.job_uuid,new Date(now)]);await appendDeliveryEvent(client,{jobUuid:row.job_uuid,stopUuid:stop.rows[0].id,eventType:"return.customer_pickup",actorType:"driver",actorPublicId:principal.driverPublicId,customerVisible:true,message:"Η επιστροφή παραλήφθηκε από τον οδηγό και είναι καθ’ οδόν προς τα καταστήματα.",now});}await client.query("COMMIT");return {ok:true,completed:false};}
  if(!parsed.stopId)throw new Error("Μη έγκυρο QR παραλαβής καταστήματος.");const stop=await client.query<{id:string;status:string;proof_hash:string|null;return_uuid:string;vendor_name:string}>(`SELECT s.id::text id,s.status,s.proof_hash,r.id::text return_uuid,vb.trading_name vendor_name FROM delivery_stops s JOIN returns r ON r.id=s.return_id JOIN vendor_businesses vb ON vb.id=s.vendor_id WHERE s.job_id=$1 AND s.public_id=$2 AND s.stop_kind='vendor_return_dropoff' LIMIT 1 FOR UPDATE OF s,r`,[row.job_uuid,parsed.stopId]);const rs=stop.rows[0];if(!rs)throw new Error("Το QR δεν αντιστοιχεί σε σημείο επιστροφής αυτής της εργασίας.");assertProofHash(token,rs.proof_hash);if(rs.status!=="completed"){if(!(await client.query("SELECT 1 FROM delivery_stops WHERE job_id=$1 AND stop_kind='customer_return_pickup' AND status='completed' LIMIT 1",[row.job_uuid])).rowCount)throw new Error("Η επιστροφή δεν έχει ακόμη παραληφθεί από τον πελάτη.");await client.query("UPDATE delivery_stops SET status='completed',completed_at=$2,completed_by_driver_id=$3,updated_at=$2 WHERE id=$1",[rs.id,new Date(now),principal.driverId]);await client.query("UPDATE returns SET status='received',received_at=COALESCE(received_at,$2),updated_at=$2 WHERE id=$1",[rs.return_uuid,new Date(now)]);await client.query(`INSERT INTO return_custody_events(id,public_id,return_id,from_party,to_party,actor_public_id,reference,note,occurred_at) VALUES($1,$2,$3,'delivery_driver','vendor',$4,$5,$6,$7)`,[randomUUID(),`return_custody_${randomUUID().replaceAll("-","")}`,rs.return_uuid,principal.driverPublicId,row.job_id,`Παράδοση επιστροφής στο ${rs.vendor_name} με QR του καταστήματος.`,new Date(now)]);await appendDeliveryEvent(client,{jobUuid:row.job_uuid,stopUuid:rs.id,eventType:"return.vendor_received",actorType:"driver",actorPublicId:principal.driverPublicId,customerVisible:true,message:`Η επιστροφή παραδόθηκε στο ${rs.vendor_name}.`,now});}const completed=!(await client.query("SELECT 1 FROM delivery_stops WHERE job_id=$1 AND status NOT IN ('completed','skipped') LIMIT 1",[row.job_uuid])).rowCount;if(completed)await client.query("UPDATE delivery_jobs SET status='completed',completed_at=$2,live_tracking_enabled=false,updated_at=$2 WHERE id=$1",[row.job_uuid,new Date(now)]);await client.query("COMMIT");return {ok:true,completed};
  }catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}
}
