import assert from "node:assert/strict";
import test from "node:test";
import { assertCustomerTryOnSaveToken, issueCustomerTryOnSaveToken } from "./try-on-security.ts";

test("Try On save tokens bind account, product, prediction and generated bytes", () => {
  const now = 1_800_000_000_000;
  const imageBytes = new Uint8Array([0xff, 0xd8, 0xff, 1, 2, 3, 4]);
  const token = issueCustomerTryOnSaveToken({
    userPublicId: "user-a",
    productId: "product-a",
    predictionId: "prediction_12345",
    imageBytes,
    now
  });

  assert.doesNotThrow(() => assertCustomerTryOnSaveToken({
    token,
    userPublicId: "user-a",
    productId: "product-a",
    predictionId: "prediction_12345",
    imageBytes,
    now: now + 1_000
  }));

  assert.throws(() => assertCustomerTryOnSaveToken({
    token,
    userPublicId: "user-b",
    productId: "product-a",
    predictionId: "prediction_12345",
    imageBytes,
    now: now + 1_000
  }), /INVALID_TRY_ON_SAVE_TOKEN/);

  assert.throws(() => assertCustomerTryOnSaveToken({
    token,
    userPublicId: "user-a",
    productId: "product-a",
    predictionId: "prediction_12345",
    imageBytes: new Uint8Array([0xff, 0xd8, 0xff, 9, 9, 9]),
    now: now + 1_000
  }), /INVALID_TRY_ON_SAVE_TOKEN/);

  assert.throws(() => assertCustomerTryOnSaveToken({
    token,
    userPublicId: "user-a",
    productId: "product-a",
    predictionId: "prediction_12345",
    imageBytes,
    now: now + 5 * 60 * 1000 + 1
  }), /TRY_ON_SAVE_TOKEN_EXPIRED/);
});
